// https://reference.opcfoundation.org/v104/Core/docs/Part6/A.1/
type AttributeId = uint32

export const AttributeIdInvalid: AttributeId = 0
export const AttributeIdNodeId: AttributeId = 1
export const AttributeIdNodeClass: AttributeId = 2
export const AttributeIdBrowseName: AttributeId = 3
export const AttributeIdDisplayName: AttributeId = 4
export const AttributeIdDescription: AttributeId = 5
export const AttributeIdWriteMask: AttributeId = 6
export const AttributeIdUserWriteMask: AttributeId = 7
export const AttributeIdIsAbstract: AttributeId = 8
export const AttributeIdSymmetric: AttributeId = 9
export const AttributeIdInverseName: AttributeId = 10
export const AttributeIdContainsNoLoops: AttributeId = 11
export const AttributeIdEventNotifier: AttributeId = 12
export const AttributeIdValue: AttributeId = 13
export const AttributeIdDataType: AttributeId = 14
export const AttributeIdValueRank: AttributeId = 15
export const AttributeIdArrayDimensions: AttributeId = 16
export const AttributeIdAccessLevel: AttributeId = 17
export const AttributeIdUserAccessLevel: AttributeId = 18
export const AttributeIdMinimumSamplingInterval: AttributeId = 19
export const AttributeIdHistorizing: AttributeId = 20
export const AttributeIdExecutable: AttributeId = 21
export const AttributeIdUserExecutable: AttributeId = 22
export const AttributeIdDataTypeDefinition: AttributeId = 23
export const AttributeIdRolePermissions: AttributeId = 24
export const AttributeIdUserRolePermissions: AttributeId = 25
export const AttributeIdAccessRestrictions: AttributeId = 26
export const AttributeIdAccessLevelEx: AttributeId = 27
