// Code generated by cmd/id. DO NOT EDIT!

export const IdDataTypeDefinition = 121
export const IdStructureDefinition = 122
export const IdEnumDefinition = 123
export const IdDataSetMetaDataType = 124
export const IdDataTypeDescription = 125
export const IdStructureDescription = 126
export const IdEnumDescription = 127
export const IdRolePermissionType = 128
export const IdNode = 260
export const IdObjectNode = 263
export const IdObjectTypeNode = 266
export const IdVariableNode = 269
export const IdVariableTypeNode = 272
export const IdReferenceTypeNode = 275
export const IdMethodNode = 278
export const IdViewNode = 281
export const IdDataTypeNode = 284
export const IdReferenceNode = 287
export const IdArgument = 298
export const IdStatusResult = 301
export const IdUserTokenPolicy = 306
export const IdApplicationDescription = 310
export const IdEndpointDescription = 314
export const IdUserIdentityToken = 318
export const IdAnonymousIdentityToken = 321
export const IdUserNameIdentityToken = 324
export const IdX509IdentityToken = 327
export const IdEndpointConfiguration = 333
export const IdBuildInfo = 340
export const IdSignedSoftwareCertificate = 346
export const IdNodeAttributes = 351
export const IdObjectAttributes = 354
export const IdVariableAttributes = 357
export const IdMethodAttributes = 360
export const IdObjectTypeAttributes = 363
export const IdVariableTypeAttributes = 366
export const IdReferenceTypeAttributes = 369
export const IdDataTypeAttributes = 372
export const IdViewAttributes = 375
export const IdAddNodesItem = 378
export const IdAddReferencesItem = 381
export const IdDeleteNodesItem = 384
export const IdDeleteReferencesItem = 387
export const IdRequestHeader = 391
export const IdResponseHeader = 394
export const IdServiceFault = 397
export const IdFindServersRequest = 422
export const IdFindServersResponse = 425
export const IdGetEndpointsRequest = 428
export const IdGetEndpointsResponse = 431
export const IdRegisteredServer = 434
export const IdRegisterServerRequest = 437
export const IdRegisterServerResponse = 440
export const IdChannelSecurityToken = 443
export const IdOpenSecureChannelRequest = 446
export const IdOpenSecureChannelResponse = 449
export const IdCloseSecureChannelRequest = 452
export const IdCloseSecureChannelResponse = 455
export const IdSignatureData = 458
export const IdCreateSessionRequest = 461
export const IdCreateSessionResponse = 464
export const IdActivateSessionRequest = 467
export const IdActivateSessionResponse = 470
export const IdCloseSessionRequest = 473
export const IdCloseSessionResponse = 476
export const IdCancelRequest = 479
export const IdCancelResponse = 482
export const IdAddNodesResult = 485
export const IdAddNodesRequest = 488
export const IdAddNodesResponse = 491
export const IdAddReferencesRequest = 494
export const IdAddReferencesResponse = 497
export const IdDeleteNodesRequest = 500
export const IdDeleteNodesResponse = 503
export const IdDeleteReferencesRequest = 506
export const IdDeleteReferencesResponse = 509
export const IdViewDescription = 513
export const IdBrowseDescription = 516
export const IdReferenceDescription = 520
export const IdBrowseResult = 524
export const IdBrowseRequest = 527
export const IdBrowseResponse = 530
export const IdBrowseNextRequest = 533
export const IdBrowseNextResponse = 536
export const IdRelativePathElement = 539
export const IdRelativePath = 542
export const IdBrowsePath = 545
export const IdBrowsePathTarget = 548
export const IdBrowsePathResult = 551
export const IdTranslateBrowsePathsToNodeIdsRequest = 554
export const IdTranslateBrowsePathsToNodeIdsResponse = 557
export const IdRegisterNodesRequest = 560
export const IdRegisterNodesResponse = 563
export const IdUnregisterNodesRequest = 566
export const IdUnregisterNodesResponse = 569
export const IdQueryDataDescription = 572
export const IdNodeTypeDescription = 575
export const IdQueryDataSet = 579
export const IdNodeReference = 582
export const IdContentFilterElement = 585
export const IdContentFilter = 588
export const IdFilterOperand = 591
export const IdElementOperand = 594
export const IdLiteralOperand = 597
export const IdAttributeOperand = 600
export const IdSimpleAttributeOperand = 603
export const IdContentFilterElementResult = 606
export const IdContentFilterResult = 609
export const IdParsingResult = 612
export const IdQueryFirstRequest = 615
export const IdQueryFirstResponse = 618
export const IdQueryNextRequest = 621
export const IdQueryNextResponse = 624
export const IdReadValueId = 628
export const IdReadRequest = 631
export const IdReadResponse = 634
export const IdHistoryReadValueId = 637
export const IdHistoryReadResult = 640
export const IdHistoryReadDetails = 643
export const IdReadEventDetails = 646
export const IdReadRawModifiedDetails = 649
export const IdReadProcessedDetails = 652
export const IdReadAtTimeDetails = 655
export const IdHistoryData = 658
export const IdHistoryEvent = 661
export const IdHistoryReadRequest = 664
export const IdHistoryReadResponse = 667
export const IdWriteValue = 670
export const IdWriteRequest = 673
export const IdWriteResponse = 676
export const IdHistoryUpdateDetails = 679
export const IdUpdateDataDetails = 682
export const IdUpdateEventDetails = 685
export const IdDeleteRawModifiedDetails = 688
export const IdDeleteAtTimeDetails = 691
export const IdDeleteEventDetails = 694
export const IdHistoryUpdateResult = 697
export const IdHistoryUpdateRequest = 700
export const IdHistoryUpdateResponse = 703
export const IdCallMethodRequest = 706
export const IdCallMethodResult = 709
export const IdCallRequest = 712
export const IdCallResponse = 715
export const IdMonitoringFilter = 721
export const IdDataChangeFilter = 724
export const IdEventFilter = 727
export const IdAggregateFilter = 730
export const IdMonitoringFilterResult = 733
export const IdEventFilterResult = 736
export const IdAggregateFilterResult = 739
export const IdMonitoringParameters = 742
export const IdMonitoredItemCreateRequest = 745
export const IdMonitoredItemCreateResult = 748
export const IdCreateMonitoredItemsRequest = 751
export const IdCreateMonitoredItemsResponse = 754
export const IdMonitoredItemModifyRequest = 757
export const IdMonitoredItemModifyResult = 760
export const IdModifyMonitoredItemsRequest = 763
export const IdModifyMonitoredItemsResponse = 766
export const IdSetMonitoringModeRequest = 769
export const IdSetMonitoringModeResponse = 772
export const IdSetTriggeringRequest = 775
export const IdSetTriggeringResponse = 778
export const IdDeleteMonitoredItemsRequest = 781
export const IdDeleteMonitoredItemsResponse = 784
export const IdCreateSubscriptionRequest = 787
export const IdCreateSubscriptionResponse = 790
export const IdModifySubscriptionRequest = 793
export const IdModifySubscriptionResponse = 796
export const IdSetPublishingModeRequest = 799
export const IdSetPublishingModeResponse = 802
export const IdNotificationMessage = 805
export const IdMonitoredItemNotification = 808
export const IdDataChangeNotification = 811
export const IdStatusChangeNotification = 820
export const IdSubscriptionAcknowledgement = 823
export const IdPublishRequest = 826
export const IdPublishResponse = 829
export const IdRepublishRequest = 832
export const IdRepublishResponse = 835
export const IdTransferResult = 838
export const IdTransferSubscriptionsRequest = 841
export const IdTransferSubscriptionsResponse = 844
export const IdDeleteSubscriptionsRequest = 847
export const IdDeleteSubscriptionsResponse = 850
export const IdRedundantServerDataType = 855
export const IdSamplingIntervalDiagnosticsDataType = 858
export const IdServerDiagnosticsSummaryDataType = 861
export const IdServerStatusDataType = 864
export const IdSessionDiagnosticsDataType = 867
export const IdSessionSecurityDiagnosticsDataType = 870
export const IdServiceCounterDataType = 873
export const IdSubscriptionDiagnosticsDataType = 876
export const IdModelChangeStructureDataType = 879
export const IdRange = 886
export const IdEUInformation = 889
export const IdAnnotation = 893
export const IdProgramDiagnosticDataType = 896
export const IdSemanticChangeStructureDataType = 899
export const IdEventNotificationList = 916
export const IdEventFieldList = 919
export const IdHistoryEventFieldList = 922
export const IdIssuedIdentityToken = 940
export const IdNotificationData = 947
export const IdAggregateConfiguration = 950
export const IdEnumValueType = 8251
export const IdTimeZoneDataType = 8917
export const IdModificationInfo = 11226
export const IdHistoryModifiedData = 11227
export const IdUpdateStructureDataDetails = 11300
export const IdInstanceNode = 11889
export const IdTypeNode = 11890
export const IdEndpointUrlListDataType = 11957
export const IdNetworkGroupDataType = 11958
export const IdAxisInformation = 12089
export const IdXVType = 12090
export const IdComplexNumberType = 12181
export const IdDoubleComplexNumberType = 12182
export const IdServerOnNetwork = 12207
export const IdFindServersOnNetworkRequest = 12208
export const IdFindServersOnNetworkResponse = 12209
export const IdRegisterServer2Request = 12211
export const IdRegisterServer2Response = 12212
export const IdTrustListDataType = 12680
export const IdOptionSet = 12765
export const IdUnion = 12766
export const IdDiscoveryConfiguration = 12900
export const IdMdnsDiscoveryConfiguration = 12901
export const IdPublishedVariableDataType = 14323
export const IdFieldMetaData = 14839
export const IdStructureField = 14844
export const IdEnumField = 14845
export const IdKeyValuePair = 14846
export const IdConfigurationVersionDataType = 14847
export const IdFieldTargetDataType = 14848
export const IdProgramDiagnostic2DataType = 15397
export const IdSimpleTypeDescription = 15421
export const IdUABinaryFileDataType = 15422
export const IdBrokerConnectionTransportDataType = 15479
export const IdEndpointType = 15671
export const IdDataTypeSchemaHeader = 15676
export const IdPublishedDataSetDataType = 15677
export const IdPublishedDataSetSourceDataType = 15678
export const IdPublishedDataItemsDataType = 15679
export const IdPublishedEventsDataType = 15681
export const IdDataSetWriterDataType = 15682
export const IdDataSetWriterTransportDataType = 15683
export const IdDataSetWriterMessageDataType = 15688
export const IdPubSubGroupDataType = 15689
export const IdWriterGroupTransportDataType = 15691
export const IdWriterGroupMessageDataType = 15693
export const IdPubSubConnectionDataType = 15694
export const IdConnectionTransportDataType = 15695
export const IdReaderGroupTransportDataType = 15701
export const IdReaderGroupMessageDataType = 15702
export const IdDataSetReaderDataType = 15703
export const IdDataSetReaderTransportDataType = 15705
export const IdDataSetReaderMessageDataType = 15706
export const IdSubscribedDataSetDataType = 15707
export const IdTargetVariablesDataType = 15712
export const IdSubscribedDataSetMirrorDataType = 15713
export const IdUadpWriterGroupMessageDataType = 15715
export const IdUadpDataSetWriterMessageDataType = 15717
export const IdUadpDataSetReaderMessageDataType = 15718
export const IdJsonWriterGroupMessageDataType = 15719
export const IdJsonDataSetWriterMessageDataType = 15724
export const IdJsonDataSetReaderMessageDataType = 15725
export const IdBrokerWriterGroupTransportDataType = 15727
export const IdBrokerDataSetWriterTransportDataType = 15729
export const IdBrokerDataSetReaderTransportDataType = 15733
export const IdIdentityMappingRuleType = 15736
export const IdSessionlessInvokeRequestType = 15903
export const IdDatagramConnectionTransportDataType = 17468
export const IdAdditionalParametersType = 17537
export const IdEphemeralKeyType = 17549
export const IdGenericAttributeValue = 17610
export const IdGenericAttributes = 17611
export const IdDecimalDataType = 17863
export const IdRationalNumber = 18815
export const IdVector = 18816
export const IdThreeDVector = 18817
export const IdCartesianCoordinates = 18818
export const IdThreeDCartesianCoordinates = 18819
export const IdOrientation = 18820
export const IdThreeDOrientation = 18821
export const IdFrame = 18822
export const IdThreeDFrame = 18823
export const IdSessionlessInvokeResponseType = 21001
export const IdWriterGroupDataType = 21150
export const IdNetworkAddressDataType = 21151
export const IdNetworkAddressUrlDataType = 21152
export const IdReaderGroupDataType = 21153
export const IdPubSubConfigurationDataType = 21154
export const IdDatagramWriterGroupTransportDataType = 21155
export const IdAliasNameDataType = 23499
export const IdReadAnnotationDataDetails = 23500
export const IdCurrencyUnitType = 23507
export const IdCurrencyUnit = 23513

export const mapIdToName = new Map([
  [121, 'DataTypeDefinition'],
  [122, 'StructureDefinition'],
  [123, 'EnumDefinition'],
  [124, 'DataSetMetaDataType'],
  [125, 'DataTypeDescription'],
  [126, 'StructureDescription'],
  [127, 'EnumDescription'],
  [128, 'RolePermissionType'],
  [260, 'Node'],
  [263, 'ObjectNode'],
  [266, 'ObjectTypeNode'],
  [269, 'VariableNode'],
  [272, 'VariableTypeNode'],
  [275, 'ReferenceTypeNode'],
  [278, 'MethodNode'],
  [281, 'ViewNode'],
  [284, 'DataTypeNode'],
  [287, 'ReferenceNode'],
  [298, 'Argument'],
  [301, 'StatusResult'],
  [306, 'UserTokenPolicy'],
  [310, 'ApplicationDescription'],
  [314, 'EndpointDescription'],
  [318, 'UserIdentityToken'],
  [321, 'AnonymousIdentityToken'],
  [324, 'UserNameIdentityToken'],
  [327, 'X509IdentityToken'],
  [333, 'EndpointConfiguration'],
  [340, 'BuildInfo'],
  [346, 'SignedSoftwareCertificate'],
  [351, 'NodeAttributes'],
  [354, 'ObjectAttributes'],
  [357, 'VariableAttributes'],
  [360, 'MethodAttributes'],
  [363, 'ObjectTypeAttributes'],
  [366, 'VariableTypeAttributes'],
  [369, 'ReferenceTypeAttributes'],
  [372, 'DataTypeAttributes'],
  [375, 'ViewAttributes'],
  [378, 'AddNodesItem'],
  [381, 'AddReferencesItem'],
  [384, 'DeleteNodesItem'],
  [387, 'DeleteReferencesItem'],
  [391, 'RequestHeader'],
  [394, 'ResponseHeader'],
  [397, 'ServiceFault'],
  [422, 'FindServersRequest'],
  [425, 'FindServersResponse'],
  [428, 'GetEndpointsRequest'],
  [431, 'GetEndpointsResponse'],
  [434, 'RegisteredServer'],
  [437, 'RegisterServerRequest'],
  [440, 'RegisterServerResponse'],
  [443, 'ChannelSecurityToken'],
  [446, 'OpenSecureChannelRequest'],
  [449, 'OpenSecureChannelResponse'],
  [452, 'CloseSecureChannelRequest'],
  [455, 'CloseSecureChannelResponse'],
  [458, 'SignatureData'],
  [461, 'CreateSessionRequest'],
  [464, 'CreateSessionResponse'],
  [467, 'ActivateSessionRequest'],
  [470, 'ActivateSessionResponse'],
  [473, 'CloseSessionRequest'],
  [476, 'CloseSessionResponse'],
  [479, 'CancelRequest'],
  [482, 'CancelResponse'],
  [485, 'AddNodesResult'],
  [488, 'AddNodesRequest'],
  [491, 'AddNodesResponse'],
  [494, 'AddReferencesRequest'],
  [497, 'AddReferencesResponse'],
  [500, 'DeleteNodesRequest'],
  [503, 'DeleteNodesResponse'],
  [506, 'DeleteReferencesRequest'],
  [509, 'DeleteReferencesResponse'],
  [513, 'ViewDescription'],
  [516, 'BrowseDescription'],
  [520, 'ReferenceDescription'],
  [524, 'BrowseResult'],
  [527, 'BrowseRequest'],
  [530, 'BrowseResponse'],
  [533, 'BrowseNextRequest'],
  [536, 'BrowseNextResponse'],
  [539, 'RelativePathElement'],
  [542, 'RelativePath'],
  [545, 'BrowsePath'],
  [548, 'BrowsePathTarget'],
  [551, 'BrowsePathResult'],
  [554, 'TranslateBrowsePathsToNodeIdsRequest'],
  [557, 'TranslateBrowsePathsToNodeIdsResponse'],
  [560, 'RegisterNodesRequest'],
  [563, 'RegisterNodesResponse'],
  [566, 'UnregisterNodesRequest'],
  [569, 'UnregisterNodesResponse'],
  [572, 'QueryDataDescription'],
  [575, 'NodeTypeDescription'],
  [579, 'QueryDataSet'],
  [582, 'NodeReference'],
  [585, 'ContentFilterElement'],
  [588, 'ContentFilter'],
  [591, 'FilterOperand'],
  [594, 'ElementOperand'],
  [597, 'LiteralOperand'],
  [600, 'AttributeOperand'],
  [603, 'SimpleAttributeOperand'],
  [606, 'ContentFilterElementResult'],
  [609, 'ContentFilterResult'],
  [612, 'ParsingResult'],
  [615, 'QueryFirstRequest'],
  [618, 'QueryFirstResponse'],
  [621, 'QueryNextRequest'],
  [624, 'QueryNextResponse'],
  [628, 'ReadValueId'],
  [631, 'ReadRequest'],
  [634, 'ReadResponse'],
  [637, 'HistoryReadValueId'],
  [640, 'HistoryReadResult'],
  [643, 'HistoryReadDetails'],
  [646, 'ReadEventDetails'],
  [649, 'ReadRawModifiedDetails'],
  [652, 'ReadProcessedDetails'],
  [655, 'ReadAtTimeDetails'],
  [658, 'HistoryData'],
  [661, 'HistoryEvent'],
  [664, 'HistoryReadRequest'],
  [667, 'HistoryReadResponse'],
  [670, 'WriteValue'],
  [673, 'WriteRequest'],
  [676, 'WriteResponse'],
  [679, 'HistoryUpdateDetails'],
  [682, 'UpdateDataDetails'],
  [685, 'UpdateEventDetails'],
  [688, 'DeleteRawModifiedDetails'],
  [691, 'DeleteAtTimeDetails'],
  [694, 'DeleteEventDetails'],
  [697, 'HistoryUpdateResult'],
  [700, 'HistoryUpdateRequest'],
  [703, 'HistoryUpdateResponse'],
  [706, 'CallMethodRequest'],
  [709, 'CallMethodResult'],
  [712, 'CallRequest'],
  [715, 'CallResponse'],
  [721, 'MonitoringFilter'],
  [724, 'DataChangeFilter'],
  [727, 'EventFilter'],
  [730, 'AggregateFilter'],
  [733, 'MonitoringFilterResult'],
  [736, 'EventFilterResult'],
  [739, 'AggregateFilterResult'],
  [742, 'MonitoringParameters'],
  [745, 'MonitoredItemCreateRequest'],
  [748, 'MonitoredItemCreateResult'],
  [751, 'CreateMonitoredItemsRequest'],
  [754, 'CreateMonitoredItemsResponse'],
  [757, 'MonitoredItemModifyRequest'],
  [760, 'MonitoredItemModifyResult'],
  [763, 'ModifyMonitoredItemsRequest'],
  [766, 'ModifyMonitoredItemsResponse'],
  [769, 'SetMonitoringModeRequest'],
  [772, 'SetMonitoringModeResponse'],
  [775, 'SetTriggeringRequest'],
  [778, 'SetTriggeringResponse'],
  [781, 'DeleteMonitoredItemsRequest'],
  [784, 'DeleteMonitoredItemsResponse'],
  [787, 'CreateSubscriptionRequest'],
  [790, 'CreateSubscriptionResponse'],
  [793, 'ModifySubscriptionRequest'],
  [796, 'ModifySubscriptionResponse'],
  [799, 'SetPublishingModeRequest'],
  [802, 'SetPublishingModeResponse'],
  [805, 'NotificationMessage'],
  [808, 'MonitoredItemNotification'],
  [811, 'DataChangeNotification'],
  [820, 'StatusChangeNotification'],
  [823, 'SubscriptionAcknowledgement'],
  [826, 'PublishRequest'],
  [829, 'PublishResponse'],
  [832, 'RepublishRequest'],
  [835, 'RepublishResponse'],
  [838, 'TransferResult'],
  [841, 'TransferSubscriptionsRequest'],
  [844, 'TransferSubscriptionsResponse'],
  [847, 'DeleteSubscriptionsRequest'],
  [850, 'DeleteSubscriptionsResponse'],
  [855, 'RedundantServerDataType'],
  [858, 'SamplingIntervalDiagnosticsDataType'],
  [861, 'ServerDiagnosticsSummaryDataType'],
  [864, 'ServerStatusDataType'],
  [867, 'SessionDiagnosticsDataType'],
  [870, 'SessionSecurityDiagnosticsDataType'],
  [873, 'ServiceCounterDataType'],
  [876, 'SubscriptionDiagnosticsDataType'],
  [879, 'ModelChangeStructureDataType'],
  [886, 'Range'],
  [889, 'EUInformation'],
  [893, 'Annotation'],
  [896, 'ProgramDiagnosticDataType'],
  [899, 'SemanticChangeStructureDataType'],
  [916, 'EventNotificationList'],
  [919, 'EventFieldList'],
  [922, 'HistoryEventFieldList'],
  [940, 'IssuedIdentityToken'],
  [947, 'NotificationData'],
  [950, 'AggregateConfiguration'],
  [8251, 'EnumValueType'],
  [8917, 'TimeZoneDataType'],
  [11226, 'ModificationInfo'],
  [11227, 'HistoryModifiedData'],
  [11300, 'UpdateStructureDataDetails'],
  [11889, 'InstanceNode'],
  [11890, 'TypeNode'],
  [11957, 'EndpointUrlListDataType'],
  [11958, 'NetworkGroupDataType'],
  [12089, 'AxisInformation'],
  [12090, 'XVType'],
  [12181, 'ComplexNumberType'],
  [12182, 'DoubleComplexNumberType'],
  [12207, 'ServerOnNetwork'],
  [12208, 'FindServersOnNetworkRequest'],
  [12209, 'FindServersOnNetworkResponse'],
  [12211, 'RegisterServer2Request'],
  [12212, 'RegisterServer2Response'],
  [12680, 'TrustListDataType'],
  [12765, 'OptionSet'],
  [12766, 'Union'],
  [12900, 'DiscoveryConfiguration'],
  [12901, 'MdnsDiscoveryConfiguration'],
  [14323, 'PublishedVariableDataType'],
  [14839, 'FieldMetaData'],
  [14844, 'StructureField'],
  [14845, 'EnumField'],
  [14846, 'KeyValuePair'],
  [14847, 'ConfigurationVersionDataType'],
  [14848, 'FieldTargetDataType'],
  [15397, 'ProgramDiagnostic2DataType'],
  [15421, 'SimpleTypeDescription'],
  [15422, 'UABinaryFileDataType'],
  [15479, 'BrokerConnectionTransportDataType'],
  [15671, 'EndpointType'],
  [15676, 'DataTypeSchemaHeader'],
  [15677, 'PublishedDataSetDataType'],
  [15678, 'PublishedDataSetSourceDataType'],
  [15679, 'PublishedDataItemsDataType'],
  [15681, 'PublishedEventsDataType'],
  [15682, 'DataSetWriterDataType'],
  [15683, 'DataSetWriterTransportDataType'],
  [15688, 'DataSetWriterMessageDataType'],
  [15689, 'PubSubGroupDataType'],
  [15691, 'WriterGroupTransportDataType'],
  [15693, 'WriterGroupMessageDataType'],
  [15694, 'PubSubConnectionDataType'],
  [15695, 'ConnectionTransportDataType'],
  [15701, 'ReaderGroupTransportDataType'],
  [15702, 'ReaderGroupMessageDataType'],
  [15703, 'DataSetReaderDataType'],
  [15705, 'DataSetReaderTransportDataType'],
  [15706, 'DataSetReaderMessageDataType'],
  [15707, 'SubscribedDataSetDataType'],
  [15712, 'TargetVariablesDataType'],
  [15713, 'SubscribedDataSetMirrorDataType'],
  [15715, 'UadpWriterGroupMessageDataType'],
  [15717, 'UadpDataSetWriterMessageDataType'],
  [15718, 'UadpDataSetReaderMessageDataType'],
  [15719, 'JsonWriterGroupMessageDataType'],
  [15724, 'JsonDataSetWriterMessageDataType'],
  [15725, 'JsonDataSetReaderMessageDataType'],
  [15727, 'BrokerWriterGroupTransportDataType'],
  [15729, 'BrokerDataSetWriterTransportDataType'],
  [15733, 'BrokerDataSetReaderTransportDataType'],
  [15736, 'IdentityMappingRuleType'],
  [15903, 'SessionlessInvokeRequestType'],
  [17468, 'DatagramConnectionTransportDataType'],
  [17537, 'AdditionalParametersType'],
  [17549, 'EphemeralKeyType'],
  [17610, 'GenericAttributeValue'],
  [17611, 'GenericAttributes'],
  [17863, 'DecimalDataType'],
  [18815, 'RationalNumber'],
  [18816, 'Vector'],
  [18817, 'ThreeDVector'],
  [18818, 'CartesianCoordinates'],
  [18819, 'ThreeDCartesianCoordinates'],
  [18820, 'Orientation'],
  [18821, 'ThreeDOrientation'],
  [18822, 'Frame'],
  [18823, 'ThreeDFrame'],
  [21001, 'SessionlessInvokeResponseType'],
  [21150, 'WriterGroupDataType'],
  [21151, 'NetworkAddressDataType'],
  [21152, 'NetworkAddressUrlDataType'],
  [21153, 'ReaderGroupDataType'],
  [21154, 'PubSubConfigurationDataType'],
  [21155, 'DatagramWriterGroupTransportDataType'],
  [23499, 'AliasNameDataType'],
  [23500, 'ReadAnnotationDataDetails'],
  [23507, 'CurrencyUnitType'],
  [23513, 'CurrencyUnit']
])

export const mapNameToId = new Map([
  ['DataTypeDefinition', 121],
  ['StructureDefinition', 122],
  ['EnumDefinition', 123],
  ['DataSetMetaDataType', 124],
  ['DataTypeDescription', 125],
  ['StructureDescription', 126],
  ['EnumDescription', 127],
  ['RolePermissionType', 128],
  ['Node', 260],
  ['ObjectNode', 263],
  ['ObjectTypeNode', 266],
  ['VariableNode', 269],
  ['VariableTypeNode', 272],
  ['ReferenceTypeNode', 275],
  ['MethodNode', 278],
  ['ViewNode', 281],
  ['DataTypeNode', 284],
  ['ReferenceNode', 287],
  ['Argument', 298],
  ['StatusResult', 301],
  ['UserTokenPolicy', 306],
  ['ApplicationDescription', 310],
  ['EndpointDescription', 314],
  ['UserIdentityToken', 318],
  ['AnonymousIdentityToken', 321],
  ['UserNameIdentityToken', 324],
  ['X509IdentityToken', 327],
  ['EndpointConfiguration', 333],
  ['BuildInfo', 340],
  ['SignedSoftwareCertificate', 346],
  ['NodeAttributes', 351],
  ['ObjectAttributes', 354],
  ['VariableAttributes', 357],
  ['MethodAttributes', 360],
  ['ObjectTypeAttributes', 363],
  ['VariableTypeAttributes', 366],
  ['ReferenceTypeAttributes', 369],
  ['DataTypeAttributes', 372],
  ['ViewAttributes', 375],
  ['AddNodesItem', 378],
  ['AddReferencesItem', 381],
  ['DeleteNodesItem', 384],
  ['DeleteReferencesItem', 387],
  ['RequestHeader', 391],
  ['ResponseHeader', 394],
  ['ServiceFault', 397],
  ['FindServersRequest', 422],
  ['FindServersResponse', 425],
  ['GetEndpointsRequest', 428],
  ['GetEndpointsResponse', 431],
  ['RegisteredServer', 434],
  ['RegisterServerRequest', 437],
  ['RegisterServerResponse', 440],
  ['ChannelSecurityToken', 443],
  ['OpenSecureChannelRequest', 446],
  ['OpenSecureChannelResponse', 449],
  ['CloseSecureChannelRequest', 452],
  ['CloseSecureChannelResponse', 455],
  ['SignatureData', 458],
  ['CreateSessionRequest', 461],
  ['CreateSessionResponse', 464],
  ['ActivateSessionRequest', 467],
  ['ActivateSessionResponse', 470],
  ['CloseSessionRequest', 473],
  ['CloseSessionResponse', 476],
  ['CancelRequest', 479],
  ['CancelResponse', 482],
  ['AddNodesResult', 485],
  ['AddNodesRequest', 488],
  ['AddNodesResponse', 491],
  ['AddReferencesRequest', 494],
  ['AddReferencesResponse', 497],
  ['DeleteNodesRequest', 500],
  ['DeleteNodesResponse', 503],
  ['DeleteReferencesRequest', 506],
  ['DeleteReferencesResponse', 509],
  ['ViewDescription', 513],
  ['BrowseDescription', 516],
  ['ReferenceDescription', 520],
  ['BrowseResult', 524],
  ['BrowseRequest', 527],
  ['BrowseResponse', 530],
  ['BrowseNextRequest', 533],
  ['BrowseNextResponse', 536],
  ['RelativePathElement', 539],
  ['RelativePath', 542],
  ['BrowsePath', 545],
  ['BrowsePathTarget', 548],
  ['BrowsePathResult', 551],
  ['TranslateBrowsePathsToNodeIdsRequest', 554],
  ['TranslateBrowsePathsToNodeIdsResponse', 557],
  ['RegisterNodesRequest', 560],
  ['RegisterNodesResponse', 563],
  ['UnregisterNodesRequest', 566],
  ['UnregisterNodesResponse', 569],
  ['QueryDataDescription', 572],
  ['NodeTypeDescription', 575],
  ['QueryDataSet', 579],
  ['NodeReference', 582],
  ['ContentFilterElement', 585],
  ['ContentFilter', 588],
  ['FilterOperand', 591],
  ['ElementOperand', 594],
  ['LiteralOperand', 597],
  ['AttributeOperand', 600],
  ['SimpleAttributeOperand', 603],
  ['ContentFilterElementResult', 606],
  ['ContentFilterResult', 609],
  ['ParsingResult', 612],
  ['QueryFirstRequest', 615],
  ['QueryFirstResponse', 618],
  ['QueryNextRequest', 621],
  ['QueryNextResponse', 624],
  ['ReadValueId', 628],
  ['ReadRequest', 631],
  ['ReadResponse', 634],
  ['HistoryReadValueId', 637],
  ['HistoryReadResult', 640],
  ['HistoryReadDetails', 643],
  ['ReadEventDetails', 646],
  ['ReadRawModifiedDetails', 649],
  ['ReadProcessedDetails', 652],
  ['ReadAtTimeDetails', 655],
  ['HistoryData', 658],
  ['HistoryEvent', 661],
  ['HistoryReadRequest', 664],
  ['HistoryReadResponse', 667],
  ['WriteValue', 670],
  ['WriteRequest', 673],
  ['WriteResponse', 676],
  ['HistoryUpdateDetails', 679],
  ['UpdateDataDetails', 682],
  ['UpdateEventDetails', 685],
  ['DeleteRawModifiedDetails', 688],
  ['DeleteAtTimeDetails', 691],
  ['DeleteEventDetails', 694],
  ['HistoryUpdateResult', 697],
  ['HistoryUpdateRequest', 700],
  ['HistoryUpdateResponse', 703],
  ['CallMethodRequest', 706],
  ['CallMethodResult', 709],
  ['CallRequest', 712],
  ['CallResponse', 715],
  ['MonitoringFilter', 721],
  ['DataChangeFilter', 724],
  ['EventFilter', 727],
  ['AggregateFilter', 730],
  ['MonitoringFilterResult', 733],
  ['EventFilterResult', 736],
  ['AggregateFilterResult', 739],
  ['MonitoringParameters', 742],
  ['MonitoredItemCreateRequest', 745],
  ['MonitoredItemCreateResult', 748],
  ['CreateMonitoredItemsRequest', 751],
  ['CreateMonitoredItemsResponse', 754],
  ['MonitoredItemModifyRequest', 757],
  ['MonitoredItemModifyResult', 760],
  ['ModifyMonitoredItemsRequest', 763],
  ['ModifyMonitoredItemsResponse', 766],
  ['SetMonitoringModeRequest', 769],
  ['SetMonitoringModeResponse', 772],
  ['SetTriggeringRequest', 775],
  ['SetTriggeringResponse', 778],
  ['DeleteMonitoredItemsRequest', 781],
  ['DeleteMonitoredItemsResponse', 784],
  ['CreateSubscriptionRequest', 787],
  ['CreateSubscriptionResponse', 790],
  ['ModifySubscriptionRequest', 793],
  ['ModifySubscriptionResponse', 796],
  ['SetPublishingModeRequest', 799],
  ['SetPublishingModeResponse', 802],
  ['NotificationMessage', 805],
  ['MonitoredItemNotification', 808],
  ['DataChangeNotification', 811],
  ['StatusChangeNotification', 820],
  ['SubscriptionAcknowledgement', 823],
  ['PublishRequest', 826],
  ['PublishResponse', 829],
  ['RepublishRequest', 832],
  ['RepublishResponse', 835],
  ['TransferResult', 838],
  ['TransferSubscriptionsRequest', 841],
  ['TransferSubscriptionsResponse', 844],
  ['DeleteSubscriptionsRequest', 847],
  ['DeleteSubscriptionsResponse', 850],
  ['RedundantServerDataType', 855],
  ['SamplingIntervalDiagnosticsDataType', 858],
  ['ServerDiagnosticsSummaryDataType', 861],
  ['ServerStatusDataType', 864],
  ['SessionDiagnosticsDataType', 867],
  ['SessionSecurityDiagnosticsDataType', 870],
  ['ServiceCounterDataType', 873],
  ['SubscriptionDiagnosticsDataType', 876],
  ['ModelChangeStructureDataType', 879],
  ['Range', 886],
  ['EUInformation', 889],
  ['Annotation', 893],
  ['ProgramDiagnosticDataType', 896],
  ['SemanticChangeStructureDataType', 899],
  ['EventNotificationList', 916],
  ['EventFieldList', 919],
  ['HistoryEventFieldList', 922],
  ['IssuedIdentityToken', 940],
  ['NotificationData', 947],
  ['AggregateConfiguration', 950],
  ['EnumValueType', 8251],
  ['TimeZoneDataType', 8917],
  ['ModificationInfo', 11226],
  ['HistoryModifiedData', 11227],
  ['UpdateStructureDataDetails', 11300],
  ['InstanceNode', 11889],
  ['TypeNode', 11890],
  ['EndpointUrlListDataType', 11957],
  ['NetworkGroupDataType', 11958],
  ['AxisInformation', 12089],
  ['XVType', 12090],
  ['ComplexNumberType', 12181],
  ['DoubleComplexNumberType', 12182],
  ['ServerOnNetwork', 12207],
  ['FindServersOnNetworkRequest', 12208],
  ['FindServersOnNetworkResponse', 12209],
  ['RegisterServer2Request', 12211],
  ['RegisterServer2Response', 12212],
  ['TrustListDataType', 12680],
  ['OptionSet', 12765],
  ['Union', 12766],
  ['DiscoveryConfiguration', 12900],
  ['MdnsDiscoveryConfiguration', 12901],
  ['PublishedVariableDataType', 14323],
  ['FieldMetaData', 14839],
  ['StructureField', 14844],
  ['EnumField', 14845],
  ['KeyValuePair', 14846],
  ['ConfigurationVersionDataType', 14847],
  ['FieldTargetDataType', 14848],
  ['ProgramDiagnostic2DataType', 15397],
  ['SimpleTypeDescription', 15421],
  ['UABinaryFileDataType', 15422],
  ['BrokerConnectionTransportDataType', 15479],
  ['EndpointType', 15671],
  ['DataTypeSchemaHeader', 15676],
  ['PublishedDataSetDataType', 15677],
  ['PublishedDataSetSourceDataType', 15678],
  ['PublishedDataItemsDataType', 15679],
  ['PublishedEventsDataType', 15681],
  ['DataSetWriterDataType', 15682],
  ['DataSetWriterTransportDataType', 15683],
  ['DataSetWriterMessageDataType', 15688],
  ['PubSubGroupDataType', 15689],
  ['WriterGroupTransportDataType', 15691],
  ['WriterGroupMessageDataType', 15693],
  ['PubSubConnectionDataType', 15694],
  ['ConnectionTransportDataType', 15695],
  ['ReaderGroupTransportDataType', 15701],
  ['ReaderGroupMessageDataType', 15702],
  ['DataSetReaderDataType', 15703],
  ['DataSetReaderTransportDataType', 15705],
  ['DataSetReaderMessageDataType', 15706],
  ['SubscribedDataSetDataType', 15707],
  ['TargetVariablesDataType', 15712],
  ['SubscribedDataSetMirrorDataType', 15713],
  ['UadpWriterGroupMessageDataType', 15715],
  ['UadpDataSetWriterMessageDataType', 15717],
  ['UadpDataSetReaderMessageDataType', 15718],
  ['JsonWriterGroupMessageDataType', 15719],
  ['JsonDataSetWriterMessageDataType', 15724],
  ['JsonDataSetReaderMessageDataType', 15725],
  ['BrokerWriterGroupTransportDataType', 15727],
  ['BrokerDataSetWriterTransportDataType', 15729],
  ['BrokerDataSetReaderTransportDataType', 15733],
  ['IdentityMappingRuleType', 15736],
  ['SessionlessInvokeRequestType', 15903],
  ['DatagramConnectionTransportDataType', 17468],
  ['AdditionalParametersType', 17537],
  ['EphemeralKeyType', 17549],
  ['GenericAttributeValue', 17610],
  ['GenericAttributes', 17611],
  ['DecimalDataType', 17863],
  ['RationalNumber', 18815],
  ['Vector', 18816],
  ['ThreeDVector', 18817],
  ['CartesianCoordinates', 18818],
  ['ThreeDCartesianCoordinates', 18819],
  ['Orientation', 18820],
  ['ThreeDOrientation', 18821],
  ['Frame', 18822],
  ['ThreeDFrame', 18823],
  ['SessionlessInvokeResponseType', 21001],
  ['WriterGroupDataType', 21150],
  ['NetworkAddressDataType', 21151],
  ['NetworkAddressUrlDataType', 21152],
  ['ReaderGroupDataType', 21153],
  ['PubSubConfigurationDataType', 21154],
  ['DatagramWriterGroupTransportDataType', 21155],
  ['AliasNameDataType', 23499],
  ['ReadAnnotationDataDetails', 23500],
  ['CurrencyUnitType', 23507],
  ['CurrencyUnit', 23513]
])
