// Code generated by cmd/id. DO NOT EDIT!

export const IdBoolean = 1
export const IdSByte = 2
export const IdByte = 3
export const IdInt16 = 4
export const IdUInt16 = 5
export const IdInt32 = 6
export const IdUInt32 = 7
export const IdInt64 = 8
export const IdUInt64 = 9
export const IdFloat = 10
export const IdDouble = 11
export const IdString = 12
export const IdDateTime = 13
export const IdGuid = 14
export const IdByteString = 15
export const IdXmlElement = 16
export const IdNodeId = 17
export const IdExpandedNodeId = 18
export const IdStatusCode = 19
export const IdQualifiedName = 20
export const IdLocalizedText = 21
export const IdStructure = 22
export const IdDataValue = 23
export const IdBaseDataType = 24
export const IdDiagnosticInfo = 25
export const IdNumber = 26
export const IdInteger = 27
export const IdUInteger = 28
export const IdEnumeration = 29
export const IdImage = 30
export const IdReferences = 31
export const IdNonHierarchicalReferences = 32
export const IdHierarchicalReferences = 33
export const IdHasChild = 34
export const IdOrganizes = 35
export const IdHasEventSource = 36
export const IdHasModellingRule = 37
export const IdHasEncoding = 38
export const IdHasDescription = 39
export const IdHasTypeDefinition = 40
export const IdGeneratesEvent = 41
export const IdAggregates = 44
export const IdHasSubtype = 45
export const IdHasProperty = 46
export const IdHasComponent = 47
export const IdHasNotifier = 48
export const IdHasOrderedComponent = 49
export const IdDecimal = 50
export const IdFromState = 51
export const IdToState = 52
export const IdHasCause = 53
export const IdHasEffect = 54
export const IdHasHistoricalConfiguration = 56
export const IdBaseObjectType = 58
export const IdFolderType = 61
export const IdBaseVariableType = 62
export const IdBaseDataVariableType = 63
export const IdPropertyType = 68
export const IdDataTypeDescriptionType = 69
export const IdDataTypeDictionaryType = 72
export const IdDataTypeSystemType = 75
export const IdDataTypeEncodingType = 76
export const IdModellingRuleType = 77
export const IdModellingRuleMandatory = 78
export const IdModellingRuleOptional = 80
export const IdModellingRuleExposesItsArray = 83
export const IdRootFolder = 84
export const IdObjectsFolder = 85
export const IdTypesFolder = 86
export const IdViewsFolder = 87
export const IdObjectTypesFolder = 88
export const IdVariableTypesFolder = 89
export const IdDataTypesFolder = 90
export const IdReferenceTypesFolder = 91
export const IdXmlSchemaTypeSystem = 92
export const IdOPCBinarySchemaTypeSystem = 93
export const IdPermissionType = 94
export const IdAccessRestrictionType = 95
export const IdRolePermissionType = 96
export const IdDataTypeDefinition = 97
export const IdStructureType = 98
export const IdStructureDefinition = 99
export const IdEnumDefinition = 100
export const IdStructureField = 101
export const IdEnumField = 102
export const IdDataTypeDescriptionTypeDataTypeVersion = 104
export const IdDataTypeDescriptionTypeDictionaryFragment = 105
export const IdDataTypeDictionaryTypeDataTypeVersion = 106
export const IdDataTypeDictionaryTypeNamespaceUri = 107
export const IdModellingRuleTypeNamingRule = 111
export const IdModellingRuleMandatoryNamingRule = 112
export const IdModellingRuleOptionalNamingRule = 113
export const IdModellingRuleExposesItsArrayNamingRule = 114
export const IdHasSubStateMachine = 117
export const IdNamingRuleType = 120
export const IdDataTypeDefinitionEncodingDefaultBinary = 121
export const IdStructureDefinitionEncodingDefaultBinary = 122
export const IdEnumDefinitionEncodingDefaultBinary = 123
export const IdDataSetMetaDataTypeEncodingDefaultBinary = 124
export const IdDataTypeDescriptionEncodingDefaultBinary = 125
export const IdStructureDescriptionEncodingDefaultBinary = 126
export const IdEnumDescriptionEncodingDefaultBinary = 127
export const IdRolePermissionTypeEncodingDefaultBinary = 128
export const IdHasArgumentDescription = 129
export const IdHasOptionalInputArgumentDescription = 131
export const IdIdType = 256
export const IdNodeClass = 257
export const IdNode = 258
export const IdNodeEncodingDefaultXml = 259
export const IdNodeEncodingDefaultBinary = 260
export const IdObjectNode = 261
export const IdObjectNodeEncodingDefaultXml = 262
export const IdObjectNodeEncodingDefaultBinary = 263
export const IdObjectTypeNode = 264
export const IdObjectTypeNodeEncodingDefaultXml = 265
export const IdObjectTypeNodeEncodingDefaultBinary = 266
export const IdVariableNode = 267
export const IdVariableNodeEncodingDefaultXml = 268
export const IdVariableNodeEncodingDefaultBinary = 269
export const IdVariableTypeNode = 270
export const IdVariableTypeNodeEncodingDefaultXml = 271
export const IdVariableTypeNodeEncodingDefaultBinary = 272
export const IdReferenceTypeNode = 273
export const IdReferenceTypeNodeEncodingDefaultXml = 274
export const IdReferenceTypeNodeEncodingDefaultBinary = 275
export const IdMethodNode = 276
export const IdMethodNodeEncodingDefaultXml = 277
export const IdMethodNodeEncodingDefaultBinary = 278
export const IdViewNode = 279
export const IdViewNodeEncodingDefaultXml = 280
export const IdViewNodeEncodingDefaultBinary = 281
export const IdDataTypeNode = 282
export const IdDataTypeNodeEncodingDefaultXml = 283
export const IdDataTypeNodeEncodingDefaultBinary = 284
export const IdReferenceNode = 285
export const IdReferenceNodeEncodingDefaultXml = 286
export const IdReferenceNodeEncodingDefaultBinary = 287
export const IdIntegerId = 288
export const IdCounter = 289
export const IdDuration = 290
export const IdNumericRange = 291
export const IdTime = 292
export const IdDate = 293
export const IdUtcTime = 294
export const IdLocaleId = 295
export const IdArgument = 296
export const IdArgumentEncodingDefaultXml = 297
export const IdArgumentEncodingDefaultBinary = 298
export const IdStatusResult = 299
export const IdStatusResultEncodingDefaultXml = 300
export const IdStatusResultEncodingDefaultBinary = 301
export const IdMessageSecurityMode = 302
export const IdUserTokenType = 303
export const IdUserTokenPolicy = 304
export const IdUserTokenPolicyEncodingDefaultXml = 305
export const IdUserTokenPolicyEncodingDefaultBinary = 306
export const IdApplicationType = 307
export const IdApplicationDescription = 308
export const IdApplicationDescriptionEncodingDefaultXml = 309
export const IdApplicationDescriptionEncodingDefaultBinary = 310
export const IdApplicationInstanceCertificate = 311
export const IdEndpointDescription = 312
export const IdEndpointDescriptionEncodingDefaultXml = 313
export const IdEndpointDescriptionEncodingDefaultBinary = 314
export const IdSecurityTokenRequestType = 315
export const IdUserIdentityToken = 316
export const IdUserIdentityTokenEncodingDefaultXml = 317
export const IdUserIdentityTokenEncodingDefaultBinary = 318
export const IdAnonymousIdentityToken = 319
export const IdAnonymousIdentityTokenEncodingDefaultXml = 320
export const IdAnonymousIdentityTokenEncodingDefaultBinary = 321
export const IdUserNameIdentityToken = 322
export const IdUserNameIdentityTokenEncodingDefaultXml = 323
export const IdUserNameIdentityTokenEncodingDefaultBinary = 324
export const IdX509IdentityToken = 325
export const IdX509IdentityTokenEncodingDefaultXml = 326
export const IdX509IdentityTokenEncodingDefaultBinary = 327
export const IdEndpointConfiguration = 331
export const IdEndpointConfigurationEncodingDefaultXml = 332
export const IdEndpointConfigurationEncodingDefaultBinary = 333
export const IdBuildInfo = 338
export const IdBuildInfoEncodingDefaultXml = 339
export const IdBuildInfoEncodingDefaultBinary = 340
export const IdSignedSoftwareCertificate = 344
export const IdSignedSoftwareCertificateEncodingDefaultXml = 345
export const IdSignedSoftwareCertificateEncodingDefaultBinary = 346
export const IdAttributeWriteMask = 347
export const IdNodeAttributesMask = 348
export const IdNodeAttributes = 349
export const IdNodeAttributesEncodingDefaultXml = 350
export const IdNodeAttributesEncodingDefaultBinary = 351
export const IdObjectAttributes = 352
export const IdObjectAttributesEncodingDefaultXml = 353
export const IdObjectAttributesEncodingDefaultBinary = 354
export const IdVariableAttributes = 355
export const IdVariableAttributesEncodingDefaultXml = 356
export const IdVariableAttributesEncodingDefaultBinary = 357
export const IdMethodAttributes = 358
export const IdMethodAttributesEncodingDefaultXml = 359
export const IdMethodAttributesEncodingDefaultBinary = 360
export const IdObjectTypeAttributes = 361
export const IdObjectTypeAttributesEncodingDefaultXml = 362
export const IdObjectTypeAttributesEncodingDefaultBinary = 363
export const IdVariableTypeAttributes = 364
export const IdVariableTypeAttributesEncodingDefaultXml = 365
export const IdVariableTypeAttributesEncodingDefaultBinary = 366
export const IdReferenceTypeAttributes = 367
export const IdReferenceTypeAttributesEncodingDefaultXml = 368
export const IdReferenceTypeAttributesEncodingDefaultBinary = 369
export const IdDataTypeAttributes = 370
export const IdDataTypeAttributesEncodingDefaultXml = 371
export const IdDataTypeAttributesEncodingDefaultBinary = 372
export const IdViewAttributes = 373
export const IdViewAttributesEncodingDefaultXml = 374
export const IdViewAttributesEncodingDefaultBinary = 375
export const IdAddNodesItem = 376
export const IdAddNodesItemEncodingDefaultXml = 377
export const IdAddNodesItemEncodingDefaultBinary = 378
export const IdAddReferencesItem = 379
export const IdAddReferencesItemEncodingDefaultXml = 380
export const IdAddReferencesItemEncodingDefaultBinary = 381
export const IdDeleteNodesItem = 382
export const IdDeleteNodesItemEncodingDefaultXml = 383
export const IdDeleteNodesItemEncodingDefaultBinary = 384
export const IdDeleteReferencesItem = 385
export const IdDeleteReferencesItemEncodingDefaultXml = 386
export const IdDeleteReferencesItemEncodingDefaultBinary = 387
export const IdSessionAuthenticationToken = 388
export const IdRequestHeader = 389
export const IdRequestHeaderEncodingDefaultXml = 390
export const IdRequestHeaderEncodingDefaultBinary = 391
export const IdResponseHeader = 392
export const IdResponseHeaderEncodingDefaultXml = 393
export const IdResponseHeaderEncodingDefaultBinary = 394
export const IdServiceFault = 395
export const IdServiceFaultEncodingDefaultXml = 396
export const IdServiceFaultEncodingDefaultBinary = 397
export const IdFindServersRequest = 420
export const IdFindServersRequestEncodingDefaultXml = 421
export const IdFindServersRequestEncodingDefaultBinary = 422
export const IdFindServersResponse = 423
export const IdFindServersResponseEncodingDefaultXml = 424
export const IdFindServersResponseEncodingDefaultBinary = 425
export const IdGetEndpointsRequest = 426
export const IdGetEndpointsRequestEncodingDefaultXml = 427
export const IdGetEndpointsRequestEncodingDefaultBinary = 428
export const IdGetEndpointsResponse = 429
export const IdGetEndpointsResponseEncodingDefaultXml = 430
export const IdGetEndpointsResponseEncodingDefaultBinary = 431
export const IdRegisteredServer = 432
export const IdRegisteredServerEncodingDefaultXml = 433
export const IdRegisteredServerEncodingDefaultBinary = 434
export const IdRegisterServerRequest = 435
export const IdRegisterServerRequestEncodingDefaultXml = 436
export const IdRegisterServerRequestEncodingDefaultBinary = 437
export const IdRegisterServerResponse = 438
export const IdRegisterServerResponseEncodingDefaultXml = 439
export const IdRegisterServerResponseEncodingDefaultBinary = 440
export const IdChannelSecurityToken = 441
export const IdChannelSecurityTokenEncodingDefaultXml = 442
export const IdChannelSecurityTokenEncodingDefaultBinary = 443
export const IdOpenSecureChannelRequest = 444
export const IdOpenSecureChannelRequestEncodingDefaultXml = 445
export const IdOpenSecureChannelRequestEncodingDefaultBinary = 446
export const IdOpenSecureChannelResponse = 447
export const IdOpenSecureChannelResponseEncodingDefaultXml = 448
export const IdOpenSecureChannelResponseEncodingDefaultBinary = 449
export const IdCloseSecureChannelRequest = 450
export const IdCloseSecureChannelRequestEncodingDefaultXml = 451
export const IdCloseSecureChannelRequestEncodingDefaultBinary = 452
export const IdCloseSecureChannelResponse = 453
export const IdCloseSecureChannelResponseEncodingDefaultXml = 454
export const IdCloseSecureChannelResponseEncodingDefaultBinary = 455
export const IdSignatureData = 456
export const IdSignatureDataEncodingDefaultXml = 457
export const IdSignatureDataEncodingDefaultBinary = 458
export const IdCreateSessionRequest = 459
export const IdCreateSessionRequestEncodingDefaultXml = 460
export const IdCreateSessionRequestEncodingDefaultBinary = 461
export const IdCreateSessionResponse = 462
export const IdCreateSessionResponseEncodingDefaultXml = 463
export const IdCreateSessionResponseEncodingDefaultBinary = 464
export const IdActivateSessionRequest = 465
export const IdActivateSessionRequestEncodingDefaultXml = 466
export const IdActivateSessionRequestEncodingDefaultBinary = 467
export const IdActivateSessionResponse = 468
export const IdActivateSessionResponseEncodingDefaultXml = 469
export const IdActivateSessionResponseEncodingDefaultBinary = 470
export const IdCloseSessionRequest = 471
export const IdCloseSessionRequestEncodingDefaultXml = 472
export const IdCloseSessionRequestEncodingDefaultBinary = 473
export const IdCloseSessionResponse = 474
export const IdCloseSessionResponseEncodingDefaultXml = 475
export const IdCloseSessionResponseEncodingDefaultBinary = 476
export const IdCancelRequest = 477
export const IdCancelRequestEncodingDefaultXml = 478
export const IdCancelRequestEncodingDefaultBinary = 479
export const IdCancelResponse = 480
export const IdCancelResponseEncodingDefaultXml = 481
export const IdCancelResponseEncodingDefaultBinary = 482
export const IdAddNodesResult = 483
export const IdAddNodesResultEncodingDefaultXml = 484
export const IdAddNodesResultEncodingDefaultBinary = 485
export const IdAddNodesRequest = 486
export const IdAddNodesRequestEncodingDefaultXml = 487
export const IdAddNodesRequestEncodingDefaultBinary = 488
export const IdAddNodesResponse = 489
export const IdAddNodesResponseEncodingDefaultXml = 490
export const IdAddNodesResponseEncodingDefaultBinary = 491
export const IdAddReferencesRequest = 492
export const IdAddReferencesRequestEncodingDefaultXml = 493
export const IdAddReferencesRequestEncodingDefaultBinary = 494
export const IdAddReferencesResponse = 495
export const IdAddReferencesResponseEncodingDefaultXml = 496
export const IdAddReferencesResponseEncodingDefaultBinary = 497
export const IdDeleteNodesRequest = 498
export const IdDeleteNodesRequestEncodingDefaultXml = 499
export const IdDeleteNodesRequestEncodingDefaultBinary = 500
export const IdDeleteNodesResponse = 501
export const IdDeleteNodesResponseEncodingDefaultXml = 502
export const IdDeleteNodesResponseEncodingDefaultBinary = 503
export const IdDeleteReferencesRequest = 504
export const IdDeleteReferencesRequestEncodingDefaultXml = 505
export const IdDeleteReferencesRequestEncodingDefaultBinary = 506
export const IdDeleteReferencesResponse = 507
export const IdDeleteReferencesResponseEncodingDefaultXml = 508
export const IdDeleteReferencesResponseEncodingDefaultBinary = 509
export const IdBrowseDirection = 510
export const IdViewDescription = 511
export const IdViewDescriptionEncodingDefaultXml = 512
export const IdViewDescriptionEncodingDefaultBinary = 513
export const IdBrowseDescription = 514
export const IdBrowseDescriptionEncodingDefaultXml = 515
export const IdBrowseDescriptionEncodingDefaultBinary = 516
export const IdBrowseResultMask = 517
export const IdReferenceDescription = 518
export const IdReferenceDescriptionEncodingDefaultXml = 519
export const IdReferenceDescriptionEncodingDefaultBinary = 520
export const IdContinuationPoint = 521
export const IdBrowseResult = 522
export const IdBrowseResultEncodingDefaultXml = 523
export const IdBrowseResultEncodingDefaultBinary = 524
export const IdBrowseRequest = 525
export const IdBrowseRequestEncodingDefaultXml = 526
export const IdBrowseRequestEncodingDefaultBinary = 527
export const IdBrowseResponse = 528
export const IdBrowseResponseEncodingDefaultXml = 529
export const IdBrowseResponseEncodingDefaultBinary = 530
export const IdBrowseNextRequest = 531
export const IdBrowseNextRequestEncodingDefaultXml = 532
export const IdBrowseNextRequestEncodingDefaultBinary = 533
export const IdBrowseNextResponse = 534
export const IdBrowseNextResponseEncodingDefaultXml = 535
export const IdBrowseNextResponseEncodingDefaultBinary = 536
export const IdRelativePathElement = 537
export const IdRelativePathElementEncodingDefaultXml = 538
export const IdRelativePathElementEncodingDefaultBinary = 539
export const IdRelativePath = 540
export const IdRelativePathEncodingDefaultXml = 541
export const IdRelativePathEncodingDefaultBinary = 542
export const IdBrowsePath = 543
export const IdBrowsePathEncodingDefaultXml = 544
export const IdBrowsePathEncodingDefaultBinary = 545
export const IdBrowsePathTarget = 546
export const IdBrowsePathTargetEncodingDefaultXml = 547
export const IdBrowsePathTargetEncodingDefaultBinary = 548
export const IdBrowsePathResult = 549
export const IdBrowsePathResultEncodingDefaultXml = 550
export const IdBrowsePathResultEncodingDefaultBinary = 551
export const IdTranslateBrowsePathsToNodeIdsRequest = 552
export const IdTranslateBrowsePathsToNodeIdsRequestEncodingDefaultXml = 553
export const IdTranslateBrowsePathsToNodeIdsRequestEncodingDefaultBinary = 554
export const IdTranslateBrowsePathsToNodeIdsResponse = 555
export const IdTranslateBrowsePathsToNodeIdsResponseEncodingDefaultXml = 556
export const IdTranslateBrowsePathsToNodeIdsResponseEncodingDefaultBinary = 557
export const IdRegisterNodesRequest = 558
export const IdRegisterNodesRequestEncodingDefaultXml = 559
export const IdRegisterNodesRequestEncodingDefaultBinary = 560
export const IdRegisterNodesResponse = 561
export const IdRegisterNodesResponseEncodingDefaultXml = 562
export const IdRegisterNodesResponseEncodingDefaultBinary = 563
export const IdUnregisterNodesRequest = 564
export const IdUnregisterNodesRequestEncodingDefaultXml = 565
export const IdUnregisterNodesRequestEncodingDefaultBinary = 566
export const IdUnregisterNodesResponse = 567
export const IdUnregisterNodesResponseEncodingDefaultXml = 568
export const IdUnregisterNodesResponseEncodingDefaultBinary = 569
export const IdQueryDataDescription = 570
export const IdQueryDataDescriptionEncodingDefaultXml = 571
export const IdQueryDataDescriptionEncodingDefaultBinary = 572
export const IdNodeTypeDescription = 573
export const IdNodeTypeDescriptionEncodingDefaultXml = 574
export const IdNodeTypeDescriptionEncodingDefaultBinary = 575
export const IdFilterOperator = 576
export const IdQueryDataSet = 577
export const IdQueryDataSetEncodingDefaultXml = 578
export const IdQueryDataSetEncodingDefaultBinary = 579
export const IdNodeReference = 580
export const IdNodeReferenceEncodingDefaultXml = 581
export const IdNodeReferenceEncodingDefaultBinary = 582
export const IdContentFilterElement = 583
export const IdContentFilterElementEncodingDefaultXml = 584
export const IdContentFilterElementEncodingDefaultBinary = 585
export const IdContentFilter = 586
export const IdContentFilterEncodingDefaultXml = 587
export const IdContentFilterEncodingDefaultBinary = 588
export const IdFilterOperand = 589
export const IdFilterOperandEncodingDefaultXml = 590
export const IdFilterOperandEncodingDefaultBinary = 591
export const IdElementOperand = 592
export const IdElementOperandEncodingDefaultXml = 593
export const IdElementOperandEncodingDefaultBinary = 594
export const IdLiteralOperand = 595
export const IdLiteralOperandEncodingDefaultXml = 596
export const IdLiteralOperandEncodingDefaultBinary = 597
export const IdAttributeOperand = 598
export const IdAttributeOperandEncodingDefaultXml = 599
export const IdAttributeOperandEncodingDefaultBinary = 600
export const IdSimpleAttributeOperand = 601
export const IdSimpleAttributeOperandEncodingDefaultXml = 602
export const IdSimpleAttributeOperandEncodingDefaultBinary = 603
export const IdContentFilterElementResult = 604
export const IdContentFilterElementResultEncodingDefaultXml = 605
export const IdContentFilterElementResultEncodingDefaultBinary = 606
export const IdContentFilterResult = 607
export const IdContentFilterResultEncodingDefaultXml = 608
export const IdContentFilterResultEncodingDefaultBinary = 609
export const IdParsingResult = 610
export const IdParsingResultEncodingDefaultXml = 611
export const IdParsingResultEncodingDefaultBinary = 612
export const IdQueryFirstRequest = 613
export const IdQueryFirstRequestEncodingDefaultXml = 614
export const IdQueryFirstRequestEncodingDefaultBinary = 615
export const IdQueryFirstResponse = 616
export const IdQueryFirstResponseEncodingDefaultXml = 617
export const IdQueryFirstResponseEncodingDefaultBinary = 618
export const IdQueryNextRequest = 619
export const IdQueryNextRequestEncodingDefaultXml = 620
export const IdQueryNextRequestEncodingDefaultBinary = 621
export const IdQueryNextResponse = 622
export const IdQueryNextResponseEncodingDefaultXml = 623
export const IdQueryNextResponseEncodingDefaultBinary = 624
export const IdTimestampsToReturn = 625
export const IdReadValueId = 626
export const IdReadValueIdEncodingDefaultXml = 627
export const IdReadValueIdEncodingDefaultBinary = 628
export const IdReadRequest = 629
export const IdReadRequestEncodingDefaultXml = 630
export const IdReadRequestEncodingDefaultBinary = 631
export const IdReadResponse = 632
export const IdReadResponseEncodingDefaultXml = 633
export const IdReadResponseEncodingDefaultBinary = 634
export const IdHistoryReadValueId = 635
export const IdHistoryReadValueIdEncodingDefaultXml = 636
export const IdHistoryReadValueIdEncodingDefaultBinary = 637
export const IdHistoryReadResult = 638
export const IdHistoryReadResultEncodingDefaultXml = 639
export const IdHistoryReadResultEncodingDefaultBinary = 640
export const IdHistoryReadDetails = 641
export const IdHistoryReadDetailsEncodingDefaultXml = 642
export const IdHistoryReadDetailsEncodingDefaultBinary = 643
export const IdReadEventDetails = 644
export const IdReadEventDetailsEncodingDefaultXml = 645
export const IdReadEventDetailsEncodingDefaultBinary = 646
export const IdReadRawModifiedDetails = 647
export const IdReadRawModifiedDetailsEncodingDefaultXml = 648
export const IdReadRawModifiedDetailsEncodingDefaultBinary = 649
export const IdReadProcessedDetails = 650
export const IdReadProcessedDetailsEncodingDefaultXml = 651
export const IdReadProcessedDetailsEncodingDefaultBinary = 652
export const IdReadAtTimeDetails = 653
export const IdReadAtTimeDetailsEncodingDefaultXml = 654
export const IdReadAtTimeDetailsEncodingDefaultBinary = 655
export const IdHistoryData = 656
export const IdHistoryDataEncodingDefaultXml = 657
export const IdHistoryDataEncodingDefaultBinary = 658
export const IdHistoryEvent = 659
export const IdHistoryEventEncodingDefaultXml = 660
export const IdHistoryEventEncodingDefaultBinary = 661
export const IdHistoryReadRequest = 662
export const IdHistoryReadRequestEncodingDefaultXml = 663
export const IdHistoryReadRequestEncodingDefaultBinary = 664
export const IdHistoryReadResponse = 665
export const IdHistoryReadResponseEncodingDefaultXml = 666
export const IdHistoryReadResponseEncodingDefaultBinary = 667
export const IdWriteValue = 668
export const IdWriteValueEncodingDefaultXml = 669
export const IdWriteValueEncodingDefaultBinary = 670
export const IdWriteRequest = 671
export const IdWriteRequestEncodingDefaultXml = 672
export const IdWriteRequestEncodingDefaultBinary = 673
export const IdWriteResponse = 674
export const IdWriteResponseEncodingDefaultXml = 675
export const IdWriteResponseEncodingDefaultBinary = 676
export const IdHistoryUpdateDetails = 677
export const IdHistoryUpdateDetailsEncodingDefaultXml = 678
export const IdHistoryUpdateDetailsEncodingDefaultBinary = 679
export const IdUpdateDataDetails = 680
export const IdUpdateDataDetailsEncodingDefaultXml = 681
export const IdUpdateDataDetailsEncodingDefaultBinary = 682
export const IdUpdateEventDetails = 683
export const IdUpdateEventDetailsEncodingDefaultXml = 684
export const IdUpdateEventDetailsEncodingDefaultBinary = 685
export const IdDeleteRawModifiedDetails = 686
export const IdDeleteRawModifiedDetailsEncodingDefaultXml = 687
export const IdDeleteRawModifiedDetailsEncodingDefaultBinary = 688
export const IdDeleteAtTimeDetails = 689
export const IdDeleteAtTimeDetailsEncodingDefaultXml = 690
export const IdDeleteAtTimeDetailsEncodingDefaultBinary = 691
export const IdDeleteEventDetails = 692
export const IdDeleteEventDetailsEncodingDefaultXml = 693
export const IdDeleteEventDetailsEncodingDefaultBinary = 694
export const IdHistoryUpdateResult = 695
export const IdHistoryUpdateResultEncodingDefaultXml = 696
export const IdHistoryUpdateResultEncodingDefaultBinary = 697
export const IdHistoryUpdateRequest = 698
export const IdHistoryUpdateRequestEncodingDefaultXml = 699
export const IdHistoryUpdateRequestEncodingDefaultBinary = 700
export const IdHistoryUpdateResponse = 701
export const IdHistoryUpdateResponseEncodingDefaultXml = 702
export const IdHistoryUpdateResponseEncodingDefaultBinary = 703
export const IdCallMethodRequest = 704
export const IdCallMethodRequestEncodingDefaultXml = 705
export const IdCallMethodRequestEncodingDefaultBinary = 706
export const IdCallMethodResult = 707
export const IdCallMethodResultEncodingDefaultXml = 708
export const IdCallMethodResultEncodingDefaultBinary = 709
export const IdCallRequest = 710
export const IdCallRequestEncodingDefaultXml = 711
export const IdCallRequestEncodingDefaultBinary = 712
export const IdCallResponse = 713
export const IdCallResponseEncodingDefaultXml = 714
export const IdCallResponseEncodingDefaultBinary = 715
export const IdMonitoringMode = 716
export const IdDataChangeTrigger = 717
export const IdDeadbandType = 718
export const IdMonitoringFilter = 719
export const IdMonitoringFilterEncodingDefaultXml = 720
export const IdMonitoringFilterEncodingDefaultBinary = 721
export const IdDataChangeFilter = 722
export const IdDataChangeFilterEncodingDefaultXml = 723
export const IdDataChangeFilterEncodingDefaultBinary = 724
export const IdEventFilter = 725
export const IdEventFilterEncodingDefaultXml = 726
export const IdEventFilterEncodingDefaultBinary = 727
export const IdAggregateFilter = 728
export const IdAggregateFilterEncodingDefaultXml = 729
export const IdAggregateFilterEncodingDefaultBinary = 730
export const IdMonitoringFilterResult = 731
export const IdMonitoringFilterResultEncodingDefaultXml = 732
export const IdMonitoringFilterResultEncodingDefaultBinary = 733
export const IdEventFilterResult = 734
export const IdEventFilterResultEncodingDefaultXml = 735
export const IdEventFilterResultEncodingDefaultBinary = 736
export const IdAggregateFilterResult = 737
export const IdAggregateFilterResultEncodingDefaultXml = 738
export const IdAggregateFilterResultEncodingDefaultBinary = 739
export const IdMonitoringParameters = 740
export const IdMonitoringParametersEncodingDefaultXml = 741
export const IdMonitoringParametersEncodingDefaultBinary = 742
export const IdMonitoredItemCreateRequest = 743
export const IdMonitoredItemCreateRequestEncodingDefaultXml = 744
export const IdMonitoredItemCreateRequestEncodingDefaultBinary = 745
export const IdMonitoredItemCreateResult = 746
export const IdMonitoredItemCreateResultEncodingDefaultXml = 747
export const IdMonitoredItemCreateResultEncodingDefaultBinary = 748
export const IdCreateMonitoredItemsRequest = 749
export const IdCreateMonitoredItemsRequestEncodingDefaultXml = 750
export const IdCreateMonitoredItemsRequestEncodingDefaultBinary = 751
export const IdCreateMonitoredItemsResponse = 752
export const IdCreateMonitoredItemsResponseEncodingDefaultXml = 753
export const IdCreateMonitoredItemsResponseEncodingDefaultBinary = 754
export const IdMonitoredItemModifyRequest = 755
export const IdMonitoredItemModifyRequestEncodingDefaultXml = 756
export const IdMonitoredItemModifyRequestEncodingDefaultBinary = 757
export const IdMonitoredItemModifyResult = 758
export const IdMonitoredItemModifyResultEncodingDefaultXml = 759
export const IdMonitoredItemModifyResultEncodingDefaultBinary = 760
export const IdModifyMonitoredItemsRequest = 761
export const IdModifyMonitoredItemsRequestEncodingDefaultXml = 762
export const IdModifyMonitoredItemsRequestEncodingDefaultBinary = 763
export const IdModifyMonitoredItemsResponse = 764
export const IdModifyMonitoredItemsResponseEncodingDefaultXml = 765
export const IdModifyMonitoredItemsResponseEncodingDefaultBinary = 766
export const IdSetMonitoringModeRequest = 767
export const IdSetMonitoringModeRequestEncodingDefaultXml = 768
export const IdSetMonitoringModeRequestEncodingDefaultBinary = 769
export const IdSetMonitoringModeResponse = 770
export const IdSetMonitoringModeResponseEncodingDefaultXml = 771
export const IdSetMonitoringModeResponseEncodingDefaultBinary = 772
export const IdSetTriggeringRequest = 773
export const IdSetTriggeringRequestEncodingDefaultXml = 774
export const IdSetTriggeringRequestEncodingDefaultBinary = 775
export const IdSetTriggeringResponse = 776
export const IdSetTriggeringResponseEncodingDefaultXml = 777
export const IdSetTriggeringResponseEncodingDefaultBinary = 778
export const IdDeleteMonitoredItemsRequest = 779
export const IdDeleteMonitoredItemsRequestEncodingDefaultXml = 780
export const IdDeleteMonitoredItemsRequestEncodingDefaultBinary = 781
export const IdDeleteMonitoredItemsResponse = 782
export const IdDeleteMonitoredItemsResponseEncodingDefaultXml = 783
export const IdDeleteMonitoredItemsResponseEncodingDefaultBinary = 784
export const IdCreateSubscriptionRequest = 785
export const IdCreateSubscriptionRequestEncodingDefaultXml = 786
export const IdCreateSubscriptionRequestEncodingDefaultBinary = 787
export const IdCreateSubscriptionResponse = 788
export const IdCreateSubscriptionResponseEncodingDefaultXml = 789
export const IdCreateSubscriptionResponseEncodingDefaultBinary = 790
export const IdModifySubscriptionRequest = 791
export const IdModifySubscriptionRequestEncodingDefaultXml = 792
export const IdModifySubscriptionRequestEncodingDefaultBinary = 793
export const IdModifySubscriptionResponse = 794
export const IdModifySubscriptionResponseEncodingDefaultXml = 795
export const IdModifySubscriptionResponseEncodingDefaultBinary = 796
export const IdSetPublishingModeRequest = 797
export const IdSetPublishingModeRequestEncodingDefaultXml = 798
export const IdSetPublishingModeRequestEncodingDefaultBinary = 799
export const IdSetPublishingModeResponse = 800
export const IdSetPublishingModeResponseEncodingDefaultXml = 801
export const IdSetPublishingModeResponseEncodingDefaultBinary = 802
export const IdNotificationMessage = 803
export const IdNotificationMessageEncodingDefaultXml = 804
export const IdNotificationMessageEncodingDefaultBinary = 805
export const IdMonitoredItemNotification = 806
export const IdMonitoredItemNotificationEncodingDefaultXml = 807
export const IdMonitoredItemNotificationEncodingDefaultBinary = 808
export const IdDataChangeNotification = 809
export const IdDataChangeNotificationEncodingDefaultXml = 810
export const IdDataChangeNotificationEncodingDefaultBinary = 811
export const IdStatusChangeNotification = 818
export const IdStatusChangeNotificationEncodingDefaultXml = 819
export const IdStatusChangeNotificationEncodingDefaultBinary = 820
export const IdSubscriptionAcknowledgement = 821
export const IdSubscriptionAcknowledgementEncodingDefaultXml = 822
export const IdSubscriptionAcknowledgementEncodingDefaultBinary = 823
export const IdPublishRequest = 824
export const IdPublishRequestEncodingDefaultXml = 825
export const IdPublishRequestEncodingDefaultBinary = 826
export const IdPublishResponse = 827
export const IdPublishResponseEncodingDefaultXml = 828
export const IdPublishResponseEncodingDefaultBinary = 829
export const IdRepublishRequest = 830
export const IdRepublishRequestEncodingDefaultXml = 831
export const IdRepublishRequestEncodingDefaultBinary = 832
export const IdRepublishResponse = 833
export const IdRepublishResponseEncodingDefaultXml = 834
export const IdRepublishResponseEncodingDefaultBinary = 835
export const IdTransferResult = 836
export const IdTransferResultEncodingDefaultXml = 837
export const IdTransferResultEncodingDefaultBinary = 838
export const IdTransferSubscriptionsRequest = 839
export const IdTransferSubscriptionsRequestEncodingDefaultXml = 840
export const IdTransferSubscriptionsRequestEncodingDefaultBinary = 841
export const IdTransferSubscriptionsResponse = 842
export const IdTransferSubscriptionsResponseEncodingDefaultXml = 843
export const IdTransferSubscriptionsResponseEncodingDefaultBinary = 844
export const IdDeleteSubscriptionsRequest = 845
export const IdDeleteSubscriptionsRequestEncodingDefaultXml = 846
export const IdDeleteSubscriptionsRequestEncodingDefaultBinary = 847
export const IdDeleteSubscriptionsResponse = 848
export const IdDeleteSubscriptionsResponseEncodingDefaultXml = 849
export const IdDeleteSubscriptionsResponseEncodingDefaultBinary = 850
export const IdRedundancySupport = 851
export const IdServerState = 852
export const IdRedundantServerDataType = 853
export const IdRedundantServerDataTypeEncodingDefaultXml = 854
export const IdRedundantServerDataTypeEncodingDefaultBinary = 855
export const IdSamplingIntervalDiagnosticsDataType = 856
export const IdSamplingIntervalDiagnosticsDataTypeEncodingDefaultXml = 857
export const IdSamplingIntervalDiagnosticsDataTypeEncodingDefaultBinary = 858
export const IdServerDiagnosticsSummaryDataType = 859
export const IdServerDiagnosticsSummaryDataTypeEncodingDefaultXml = 860
export const IdServerDiagnosticsSummaryDataTypeEncodingDefaultBinary = 861
export const IdServerStatusDataType = 862
export const IdServerStatusDataTypeEncodingDefaultXml = 863
export const IdServerStatusDataTypeEncodingDefaultBinary = 864
export const IdSessionDiagnosticsDataType = 865
export const IdSessionDiagnosticsDataTypeEncodingDefaultXml = 866
export const IdSessionDiagnosticsDataTypeEncodingDefaultBinary = 867
export const IdSessionSecurityDiagnosticsDataType = 868
export const IdSessionSecurityDiagnosticsDataTypeEncodingDefaultXml = 869
export const IdSessionSecurityDiagnosticsDataTypeEncodingDefaultBinary = 870
export const IdServiceCounterDataType = 871
export const IdServiceCounterDataTypeEncodingDefaultXml = 872
export const IdServiceCounterDataTypeEncodingDefaultBinary = 873
export const IdSubscriptionDiagnosticsDataType = 874
export const IdSubscriptionDiagnosticsDataTypeEncodingDefaultXml = 875
export const IdSubscriptionDiagnosticsDataTypeEncodingDefaultBinary = 876
export const IdModelChangeStructureDataType = 877
export const IdModelChangeStructureDataTypeEncodingDefaultXml = 878
export const IdModelChangeStructureDataTypeEncodingDefaultBinary = 879
export const IdRange = 884
export const IdRangeEncodingDefaultXml = 885
export const IdRangeEncodingDefaultBinary = 886
export const IdEUInformation = 887
export const IdEUInformationEncodingDefaultXml = 888
export const IdEUInformationEncodingDefaultBinary = 889
export const IdExceptionDeviationFormat = 890
export const IdAnnotation = 891
export const IdAnnotationEncodingDefaultXml = 892
export const IdAnnotationEncodingDefaultBinary = 893
export const IdProgramDiagnosticDataType = 894
export const IdProgramDiagnosticDataTypeEncodingDefaultXml = 895
export const IdProgramDiagnosticDataTypeEncodingDefaultBinary = 896
export const IdSemanticChangeStructureDataType = 897
export const IdSemanticChangeStructureDataTypeEncodingDefaultXml = 898
export const IdSemanticChangeStructureDataTypeEncodingDefaultBinary = 899
export const IdEventNotificationList = 914
export const IdEventNotificationListEncodingDefaultXml = 915
export const IdEventNotificationListEncodingDefaultBinary = 916
export const IdEventFieldList = 917
export const IdEventFieldListEncodingDefaultXml = 918
export const IdEventFieldListEncodingDefaultBinary = 919
export const IdHistoryEventFieldList = 920
export const IdHistoryEventFieldListEncodingDefaultXml = 921
export const IdHistoryEventFieldListEncodingDefaultBinary = 922
export const IdIssuedIdentityToken = 938
export const IdIssuedIdentityTokenEncodingDefaultXml = 939
export const IdIssuedIdentityTokenEncodingDefaultBinary = 940
export const IdNotificationData = 945
export const IdNotificationDataEncodingDefaultXml = 946
export const IdNotificationDataEncodingDefaultBinary = 947
export const IdAggregateConfiguration = 948
export const IdAggregateConfigurationEncodingDefaultXml = 949
export const IdAggregateConfigurationEncodingDefaultBinary = 950

export const mapIdToName = new Map([
  [1, 'Boolean'],
  [2, 'SByte'],
  [3, 'Byte'],
  [4, 'Int16'],
  [5, 'UInt16'],
  [6, 'Int32'],
  [7, 'UInt32'],
  [8, 'Int64'],
  [9, 'UInt64'],
  [10, 'Float'],
  [11, 'Double'],
  [12, 'String'],
  [13, 'DateTime'],
  [14, 'Guid'],
  [15, 'ByteString'],
  [16, 'XmlElement'],
  [17, 'NodeId'],
  [18, 'ExpandedNodeId'],
  [19, 'StatusCode'],
  [20, 'QualifiedName'],
  [21, 'LocalizedText'],
  [22, 'Structure'],
  [23, 'DataValue'],
  [24, 'BaseDataType'],
  [25, 'DiagnosticInfo'],
  [26, 'Number'],
  [27, 'Integer'],
  [28, 'UInteger'],
  [29, 'Enumeration'],
  [30, 'Image'],
  [31, 'References'],
  [32, 'NonHierarchicalReferences'],
  [33, 'HierarchicalReferences'],
  [34, 'HasChild'],
  [35, 'Organizes'],
  [36, 'HasEventSource'],
  [37, 'HasModellingRule'],
  [38, 'HasEncoding'],
  [39, 'HasDescription'],
  [40, 'HasTypeDefinition'],
  [41, 'GeneratesEvent'],
  [44, 'Aggregates'],
  [45, 'HasSubtype'],
  [46, 'HasProperty'],
  [47, 'HasComponent'],
  [48, 'HasNotifier'],
  [49, 'HasOrderedComponent'],
  [50, 'Decimal'],
  [51, 'FromState'],
  [52, 'ToState'],
  [53, 'HasCause'],
  [54, 'HasEffect'],
  [56, 'HasHistoricalConfiguration'],
  [58, 'BaseObjectType'],
  [61, 'FolderType'],
  [62, 'BaseVariableType'],
  [63, 'BaseDataVariableType'],
  [68, 'PropertyType'],
  [69, 'DataTypeDescriptionType'],
  [72, 'DataTypeDictionaryType'],
  [75, 'DataTypeSystemType'],
  [76, 'DataTypeEncodingType'],
  [77, 'ModellingRuleType'],
  [78, 'ModellingRuleMandatory'],
  [80, 'ModellingRuleOptional'],
  [83, 'ModellingRuleExposesItsArray'],
  [84, 'RootFolder'],
  [85, 'ObjectsFolder'],
  [86, 'TypesFolder'],
  [87, 'ViewsFolder'],
  [88, 'ObjectTypesFolder'],
  [89, 'VariableTypesFolder'],
  [90, 'DataTypesFolder'],
  [91, 'ReferenceTypesFolder'],
  [92, 'XmlSchemaTypeSystem'],
  [93, 'OPCBinarySchemaTypeSystem'],
  [94, 'PermissionType'],
  [95, 'AccessRestrictionType'],
  [96, 'RolePermissionType'],
  [97, 'DataTypeDefinition'],
  [98, 'StructureType'],
  [99, 'StructureDefinition'],
  [100, 'EnumDefinition'],
  [101, 'StructureField'],
  [102, 'EnumField'],
  [104, 'DataTypeDescriptionTypeDataTypeVersion'],
  [105, 'DataTypeDescriptionTypeDictionaryFragment'],
  [106, 'DataTypeDictionaryTypeDataTypeVersion'],
  [107, 'DataTypeDictionaryTypeNamespaceUri'],
  [111, 'ModellingRuleTypeNamingRule'],
  [112, 'ModellingRuleMandatoryNamingRule'],
  [113, 'ModellingRuleOptionalNamingRule'],
  [114, 'ModellingRuleExposesItsArrayNamingRule'],
  [117, 'HasSubStateMachine'],
  [120, 'NamingRuleType'],
  [121, 'DataTypeDefinitionEncodingDefaultBinary'],
  [122, 'StructureDefinitionEncodingDefaultBinary'],
  [123, 'EnumDefinitionEncodingDefaultBinary'],
  [124, 'DataSetMetaDataTypeEncodingDefaultBinary'],
  [125, 'DataTypeDescriptionEncodingDefaultBinary'],
  [126, 'StructureDescriptionEncodingDefaultBinary'],
  [127, 'EnumDescriptionEncodingDefaultBinary'],
  [128, 'RolePermissionTypeEncodingDefaultBinary'],
  [129, 'HasArgumentDescription'],
  [131, 'HasOptionalInputArgumentDescription'],
  [256, 'IdType'],
  [257, 'NodeClass'],
  [258, 'Node'],
  [259, 'NodeEncodingDefaultXml'],
  [260, 'NodeEncodingDefaultBinary'],
  [261, 'ObjectNode'],
  [262, 'ObjectNodeEncodingDefaultXml'],
  [263, 'ObjectNodeEncodingDefaultBinary'],
  [264, 'ObjectTypeNode'],
  [265, 'ObjectTypeNodeEncodingDefaultXml'],
  [266, 'ObjectTypeNodeEncodingDefaultBinary'],
  [267, 'VariableNode'],
  [268, 'VariableNodeEncodingDefaultXml'],
  [269, 'VariableNodeEncodingDefaultBinary'],
  [270, 'VariableTypeNode'],
  [271, 'VariableTypeNodeEncodingDefaultXml'],
  [272, 'VariableTypeNodeEncodingDefaultBinary'],
  [273, 'ReferenceTypeNode'],
  [274, 'ReferenceTypeNodeEncodingDefaultXml'],
  [275, 'ReferenceTypeNodeEncodingDefaultBinary'],
  [276, 'MethodNode'],
  [277, 'MethodNodeEncodingDefaultXml'],
  [278, 'MethodNodeEncodingDefaultBinary'],
  [279, 'ViewNode'],
  [280, 'ViewNodeEncodingDefaultXml'],
  [281, 'ViewNodeEncodingDefaultBinary'],
  [282, 'DataTypeNode'],
  [283, 'DataTypeNodeEncodingDefaultXml'],
  [284, 'DataTypeNodeEncodingDefaultBinary'],
  [285, 'ReferenceNode'],
  [286, 'ReferenceNodeEncodingDefaultXml'],
  [287, 'ReferenceNodeEncodingDefaultBinary'],
  [288, 'IntegerId'],
  [289, 'Counter'],
  [290, 'Duration'],
  [291, 'NumericRange'],
  [292, 'Time'],
  [293, 'Date'],
  [294, 'UtcTime'],
  [295, 'LocaleId'],
  [296, 'Argument'],
  [297, 'ArgumentEncodingDefaultXml'],
  [298, 'ArgumentEncodingDefaultBinary'],
  [299, 'StatusResult'],
  [300, 'StatusResultEncodingDefaultXml'],
  [301, 'StatusResultEncodingDefaultBinary'],
  [302, 'MessageSecurityMode'],
  [303, 'UserTokenType'],
  [304, 'UserTokenPolicy'],
  [305, 'UserTokenPolicyEncodingDefaultXml'],
  [306, 'UserTokenPolicyEncodingDefaultBinary'],
  [307, 'ApplicationType'],
  [308, 'ApplicationDescription'],
  [309, 'ApplicationDescriptionEncodingDefaultXml'],
  [310, 'ApplicationDescriptionEncodingDefaultBinary'],
  [311, 'ApplicationInstanceCertificate'],
  [312, 'EndpointDescription'],
  [313, 'EndpointDescriptionEncodingDefaultXml'],
  [314, 'EndpointDescriptionEncodingDefaultBinary'],
  [315, 'SecurityTokenRequestType'],
  [316, 'UserIdentityToken'],
  [317, 'UserIdentityTokenEncodingDefaultXml'],
  [318, 'UserIdentityTokenEncodingDefaultBinary'],
  [319, 'AnonymousIdentityToken'],
  [320, 'AnonymousIdentityTokenEncodingDefaultXml'],
  [321, 'AnonymousIdentityTokenEncodingDefaultBinary'],
  [322, 'UserNameIdentityToken'],
  [323, 'UserNameIdentityTokenEncodingDefaultXml'],
  [324, 'UserNameIdentityTokenEncodingDefaultBinary'],
  [325, 'X509IdentityToken'],
  [326, 'X509IdentityTokenEncodingDefaultXml'],
  [327, 'X509IdentityTokenEncodingDefaultBinary'],
  [331, 'EndpointConfiguration'],
  [332, 'EndpointConfigurationEncodingDefaultXml'],
  [333, 'EndpointConfigurationEncodingDefaultBinary'],
  [338, 'BuildInfo'],
  [339, 'BuildInfoEncodingDefaultXml'],
  [340, 'BuildInfoEncodingDefaultBinary'],
  [344, 'SignedSoftwareCertificate'],
  [345, 'SignedSoftwareCertificateEncodingDefaultXml'],
  [346, 'SignedSoftwareCertificateEncodingDefaultBinary'],
  [347, 'AttributeWriteMask'],
  [348, 'NodeAttributesMask'],
  [349, 'NodeAttributes'],
  [350, 'NodeAttributesEncodingDefaultXml'],
  [351, 'NodeAttributesEncodingDefaultBinary'],
  [352, 'ObjectAttributes'],
  [353, 'ObjectAttributesEncodingDefaultXml'],
  [354, 'ObjectAttributesEncodingDefaultBinary'],
  [355, 'VariableAttributes'],
  [356, 'VariableAttributesEncodingDefaultXml'],
  [357, 'VariableAttributesEncodingDefaultBinary'],
  [358, 'MethodAttributes'],
  [359, 'MethodAttributesEncodingDefaultXml'],
  [360, 'MethodAttributesEncodingDefaultBinary'],
  [361, 'ObjectTypeAttributes'],
  [362, 'ObjectTypeAttributesEncodingDefaultXml'],
  [363, 'ObjectTypeAttributesEncodingDefaultBinary'],
  [364, 'VariableTypeAttributes'],
  [365, 'VariableTypeAttributesEncodingDefaultXml'],
  [366, 'VariableTypeAttributesEncodingDefaultBinary'],
  [367, 'ReferenceTypeAttributes'],
  [368, 'ReferenceTypeAttributesEncodingDefaultXml'],
  [369, 'ReferenceTypeAttributesEncodingDefaultBinary'],
  [370, 'DataTypeAttributes'],
  [371, 'DataTypeAttributesEncodingDefaultXml'],
  [372, 'DataTypeAttributesEncodingDefaultBinary'],
  [373, 'ViewAttributes'],
  [374, 'ViewAttributesEncodingDefaultXml'],
  [375, 'ViewAttributesEncodingDefaultBinary'],
  [376, 'AddNodesItem'],
  [377, 'AddNodesItemEncodingDefaultXml'],
  [378, 'AddNodesItemEncodingDefaultBinary'],
  [379, 'AddReferencesItem'],
  [380, 'AddReferencesItemEncodingDefaultXml'],
  [381, 'AddReferencesItemEncodingDefaultBinary'],
  [382, 'DeleteNodesItem'],
  [383, 'DeleteNodesItemEncodingDefaultXml'],
  [384, 'DeleteNodesItemEncodingDefaultBinary'],
  [385, 'DeleteReferencesItem'],
  [386, 'DeleteReferencesItemEncodingDefaultXml'],
  [387, 'DeleteReferencesItemEncodingDefaultBinary'],
  [388, 'SessionAuthenticationToken'],
  [389, 'RequestHeader'],
  [390, 'RequestHeaderEncodingDefaultXml'],
  [391, 'RequestHeaderEncodingDefaultBinary'],
  [392, 'ResponseHeader'],
  [393, 'ResponseHeaderEncodingDefaultXml'],
  [394, 'ResponseHeaderEncodingDefaultBinary'],
  [395, 'ServiceFault'],
  [396, 'ServiceFaultEncodingDefaultXml'],
  [397, 'ServiceFaultEncodingDefaultBinary'],
  [420, 'FindServersRequest'],
  [421, 'FindServersRequestEncodingDefaultXml'],
  [422, 'FindServersRequestEncodingDefaultBinary'],
  [423, 'FindServersResponse'],
  [424, 'FindServersResponseEncodingDefaultXml'],
  [425, 'FindServersResponseEncodingDefaultBinary'],
  [426, 'GetEndpointsRequest'],
  [427, 'GetEndpointsRequestEncodingDefaultXml'],
  [428, 'GetEndpointsRequestEncodingDefaultBinary'],
  [429, 'GetEndpointsResponse'],
  [430, 'GetEndpointsResponseEncodingDefaultXml'],
  [431, 'GetEndpointsResponseEncodingDefaultBinary'],
  [432, 'RegisteredServer'],
  [433, 'RegisteredServerEncodingDefaultXml'],
  [434, 'RegisteredServerEncodingDefaultBinary'],
  [435, 'RegisterServerRequest'],
  [436, 'RegisterServerRequestEncodingDefaultXml'],
  [437, 'RegisterServerRequestEncodingDefaultBinary'],
  [438, 'RegisterServerResponse'],
  [439, 'RegisterServerResponseEncodingDefaultXml'],
  [440, 'RegisterServerResponseEncodingDefaultBinary'],
  [441, 'ChannelSecurityToken'],
  [442, 'ChannelSecurityTokenEncodingDefaultXml'],
  [443, 'ChannelSecurityTokenEncodingDefaultBinary'],
  [444, 'OpenSecureChannelRequest'],
  [445, 'OpenSecureChannelRequestEncodingDefaultXml'],
  [446, 'OpenSecureChannelRequestEncodingDefaultBinary'],
  [447, 'OpenSecureChannelResponse'],
  [448, 'OpenSecureChannelResponseEncodingDefaultXml'],
  [449, 'OpenSecureChannelResponseEncodingDefaultBinary'],
  [450, 'CloseSecureChannelRequest'],
  [451, 'CloseSecureChannelRequestEncodingDefaultXml'],
  [452, 'CloseSecureChannelRequestEncodingDefaultBinary'],
  [453, 'CloseSecureChannelResponse'],
  [454, 'CloseSecureChannelResponseEncodingDefaultXml'],
  [455, 'CloseSecureChannelResponseEncodingDefaultBinary'],
  [456, 'SignatureData'],
  [457, 'SignatureDataEncodingDefaultXml'],
  [458, 'SignatureDataEncodingDefaultBinary'],
  [459, 'CreateSessionRequest'],
  [460, 'CreateSessionRequestEncodingDefaultXml'],
  [461, 'CreateSessionRequestEncodingDefaultBinary'],
  [462, 'CreateSessionResponse'],
  [463, 'CreateSessionResponseEncodingDefaultXml'],
  [464, 'CreateSessionResponseEncodingDefaultBinary'],
  [465, 'ActivateSessionRequest'],
  [466, 'ActivateSessionRequestEncodingDefaultXml'],
  [467, 'ActivateSessionRequestEncodingDefaultBinary'],
  [468, 'ActivateSessionResponse'],
  [469, 'ActivateSessionResponseEncodingDefaultXml'],
  [470, 'ActivateSessionResponseEncodingDefaultBinary'],
  [471, 'CloseSessionRequest'],
  [472, 'CloseSessionRequestEncodingDefaultXml'],
  [473, 'CloseSessionRequestEncodingDefaultBinary'],
  [474, 'CloseSessionResponse'],
  [475, 'CloseSessionResponseEncodingDefaultXml'],
  [476, 'CloseSessionResponseEncodingDefaultBinary'],
  [477, 'CancelRequest'],
  [478, 'CancelRequestEncodingDefaultXml'],
  [479, 'CancelRequestEncodingDefaultBinary'],
  [480, 'CancelResponse'],
  [481, 'CancelResponseEncodingDefaultXml'],
  [482, 'CancelResponseEncodingDefaultBinary'],
  [483, 'AddNodesResult'],
  [484, 'AddNodesResultEncodingDefaultXml'],
  [485, 'AddNodesResultEncodingDefaultBinary'],
  [486, 'AddNodesRequest'],
  [487, 'AddNodesRequestEncodingDefaultXml'],
  [488, 'AddNodesRequestEncodingDefaultBinary'],
  [489, 'AddNodesResponse'],
  [490, 'AddNodesResponseEncodingDefaultXml'],
  [491, 'AddNodesResponseEncodingDefaultBinary'],
  [492, 'AddReferencesRequest'],
  [493, 'AddReferencesRequestEncodingDefaultXml'],
  [494, 'AddReferencesRequestEncodingDefaultBinary'],
  [495, 'AddReferencesResponse'],
  [496, 'AddReferencesResponseEncodingDefaultXml'],
  [497, 'AddReferencesResponseEncodingDefaultBinary'],
  [498, 'DeleteNodesRequest'],
  [499, 'DeleteNodesRequestEncodingDefaultXml'],
  [500, 'DeleteNodesRequestEncodingDefaultBinary'],
  [501, 'DeleteNodesResponse'],
  [502, 'DeleteNodesResponseEncodingDefaultXml'],
  [503, 'DeleteNodesResponseEncodingDefaultBinary'],
  [504, 'DeleteReferencesRequest'],
  [505, 'DeleteReferencesRequestEncodingDefaultXml'],
  [506, 'DeleteReferencesRequestEncodingDefaultBinary'],
  [507, 'DeleteReferencesResponse'],
  [508, 'DeleteReferencesResponseEncodingDefaultXml'],
  [509, 'DeleteReferencesResponseEncodingDefaultBinary'],
  [510, 'BrowseDirection'],
  [511, 'ViewDescription'],
  [512, 'ViewDescriptionEncodingDefaultXml'],
  [513, 'ViewDescriptionEncodingDefaultBinary'],
  [514, 'BrowseDescription'],
  [515, 'BrowseDescriptionEncodingDefaultXml'],
  [516, 'BrowseDescriptionEncodingDefaultBinary'],
  [517, 'BrowseResultMask'],
  [518, 'ReferenceDescription'],
  [519, 'ReferenceDescriptionEncodingDefaultXml'],
  [520, 'ReferenceDescriptionEncodingDefaultBinary'],
  [521, 'ContinuationPoint'],
  [522, 'BrowseResult'],
  [523, 'BrowseResultEncodingDefaultXml'],
  [524, 'BrowseResultEncodingDefaultBinary'],
  [525, 'BrowseRequest'],
  [526, 'BrowseRequestEncodingDefaultXml'],
  [527, 'BrowseRequestEncodingDefaultBinary'],
  [528, 'BrowseResponse'],
  [529, 'BrowseResponseEncodingDefaultXml'],
  [530, 'BrowseResponseEncodingDefaultBinary'],
  [531, 'BrowseNextRequest'],
  [532, 'BrowseNextRequestEncodingDefaultXml'],
  [533, 'BrowseNextRequestEncodingDefaultBinary'],
  [534, 'BrowseNextResponse'],
  [535, 'BrowseNextResponseEncodingDefaultXml'],
  [536, 'BrowseNextResponseEncodingDefaultBinary'],
  [537, 'RelativePathElement'],
  [538, 'RelativePathElementEncodingDefaultXml'],
  [539, 'RelativePathElementEncodingDefaultBinary'],
  [540, 'RelativePath'],
  [541, 'RelativePathEncodingDefaultXml'],
  [542, 'RelativePathEncodingDefaultBinary'],
  [543, 'BrowsePath'],
  [544, 'BrowsePathEncodingDefaultXml'],
  [545, 'BrowsePathEncodingDefaultBinary'],
  [546, 'BrowsePathTarget'],
  [547, 'BrowsePathTargetEncodingDefaultXml'],
  [548, 'BrowsePathTargetEncodingDefaultBinary'],
  [549, 'BrowsePathResult'],
  [550, 'BrowsePathResultEncodingDefaultXml'],
  [551, 'BrowsePathResultEncodingDefaultBinary'],
  [552, 'TranslateBrowsePathsToNodeIdsRequest'],
  [553, 'TranslateBrowsePathsToNodeIdsRequestEncodingDefaultXml'],
  [554, 'TranslateBrowsePathsToNodeIdsRequestEncodingDefaultBinary'],
  [555, 'TranslateBrowsePathsToNodeIdsResponse'],
  [556, 'TranslateBrowsePathsToNodeIdsResponseEncodingDefaultXml'],
  [557, 'TranslateBrowsePathsToNodeIdsResponseEncodingDefaultBinary'],
  [558, 'RegisterNodesRequest'],
  [559, 'RegisterNodesRequestEncodingDefaultXml'],
  [560, 'RegisterNodesRequestEncodingDefaultBinary'],
  [561, 'RegisterNodesResponse'],
  [562, 'RegisterNodesResponseEncodingDefaultXml'],
  [563, 'RegisterNodesResponseEncodingDefaultBinary'],
  [564, 'UnregisterNodesRequest'],
  [565, 'UnregisterNodesRequestEncodingDefaultXml'],
  [566, 'UnregisterNodesRequestEncodingDefaultBinary'],
  [567, 'UnregisterNodesResponse'],
  [568, 'UnregisterNodesResponseEncodingDefaultXml'],
  [569, 'UnregisterNodesResponseEncodingDefaultBinary'],
  [570, 'QueryDataDescription'],
  [571, 'QueryDataDescriptionEncodingDefaultXml'],
  [572, 'QueryDataDescriptionEncodingDefaultBinary'],
  [573, 'NodeTypeDescription'],
  [574, 'NodeTypeDescriptionEncodingDefaultXml'],
  [575, 'NodeTypeDescriptionEncodingDefaultBinary'],
  [576, 'FilterOperator'],
  [577, 'QueryDataSet'],
  [578, 'QueryDataSetEncodingDefaultXml'],
  [579, 'QueryDataSetEncodingDefaultBinary'],
  [580, 'NodeReference'],
  [581, 'NodeReferenceEncodingDefaultXml'],
  [582, 'NodeReferenceEncodingDefaultBinary'],
  [583, 'ContentFilterElement'],
  [584, 'ContentFilterElementEncodingDefaultXml'],
  [585, 'ContentFilterElementEncodingDefaultBinary'],
  [586, 'ContentFilter'],
  [587, 'ContentFilterEncodingDefaultXml'],
  [588, 'ContentFilterEncodingDefaultBinary'],
  [589, 'FilterOperand'],
  [590, 'FilterOperandEncodingDefaultXml'],
  [591, 'FilterOperandEncodingDefaultBinary'],
  [592, 'ElementOperand'],
  [593, 'ElementOperandEncodingDefaultXml'],
  [594, 'ElementOperandEncodingDefaultBinary'],
  [595, 'LiteralOperand'],
  [596, 'LiteralOperandEncodingDefaultXml'],
  [597, 'LiteralOperandEncodingDefaultBinary'],
  [598, 'AttributeOperand'],
  [599, 'AttributeOperandEncodingDefaultXml'],
  [600, 'AttributeOperandEncodingDefaultBinary'],
  [601, 'SimpleAttributeOperand'],
  [602, 'SimpleAttributeOperandEncodingDefaultXml'],
  [603, 'SimpleAttributeOperandEncodingDefaultBinary'],
  [604, 'ContentFilterElementResult'],
  [605, 'ContentFilterElementResultEncodingDefaultXml'],
  [606, 'ContentFilterElementResultEncodingDefaultBinary'],
  [607, 'ContentFilterResult'],
  [608, 'ContentFilterResultEncodingDefaultXml'],
  [609, 'ContentFilterResultEncodingDefaultBinary'],
  [610, 'ParsingResult'],
  [611, 'ParsingResultEncodingDefaultXml'],
  [612, 'ParsingResultEncodingDefaultBinary'],
  [613, 'QueryFirstRequest'],
  [614, 'QueryFirstRequestEncodingDefaultXml'],
  [615, 'QueryFirstRequestEncodingDefaultBinary'],
  [616, 'QueryFirstResponse'],
  [617, 'QueryFirstResponseEncodingDefaultXml'],
  [618, 'QueryFirstResponseEncodingDefaultBinary'],
  [619, 'QueryNextRequest'],
  [620, 'QueryNextRequestEncodingDefaultXml'],
  [621, 'QueryNextRequestEncodingDefaultBinary'],
  [622, 'QueryNextResponse'],
  [623, 'QueryNextResponseEncodingDefaultXml'],
  [624, 'QueryNextResponseEncodingDefaultBinary'],
  [625, 'TimestampsToReturn'],
  [626, 'ReadValueId'],
  [627, 'ReadValueIdEncodingDefaultXml'],
  [628, 'ReadValueIdEncodingDefaultBinary'],
  [629, 'ReadRequest'],
  [630, 'ReadRequestEncodingDefaultXml'],
  [631, 'ReadRequestEncodingDefaultBinary'],
  [632, 'ReadResponse'],
  [633, 'ReadResponseEncodingDefaultXml'],
  [634, 'ReadResponseEncodingDefaultBinary'],
  [635, 'HistoryReadValueId'],
  [636, 'HistoryReadValueIdEncodingDefaultXml'],
  [637, 'HistoryReadValueIdEncodingDefaultBinary'],
  [638, 'HistoryReadResult'],
  [639, 'HistoryReadResultEncodingDefaultXml'],
  [640, 'HistoryReadResultEncodingDefaultBinary'],
  [641, 'HistoryReadDetails'],
  [642, 'HistoryReadDetailsEncodingDefaultXml'],
  [643, 'HistoryReadDetailsEncodingDefaultBinary'],
  [644, 'ReadEventDetails'],
  [645, 'ReadEventDetailsEncodingDefaultXml'],
  [646, 'ReadEventDetailsEncodingDefaultBinary'],
  [647, 'ReadRawModifiedDetails'],
  [648, 'ReadRawModifiedDetailsEncodingDefaultXml'],
  [649, 'ReadRawModifiedDetailsEncodingDefaultBinary'],
  [650, 'ReadProcessedDetails'],
  [651, 'ReadProcessedDetailsEncodingDefaultXml'],
  [652, 'ReadProcessedDetailsEncodingDefaultBinary'],
  [653, 'ReadAtTimeDetails'],
  [654, 'ReadAtTimeDetailsEncodingDefaultXml'],
  [655, 'ReadAtTimeDetailsEncodingDefaultBinary'],
  [656, 'HistoryData'],
  [657, 'HistoryDataEncodingDefaultXml'],
  [658, 'HistoryDataEncodingDefaultBinary'],
  [659, 'HistoryEvent'],
  [660, 'HistoryEventEncodingDefaultXml'],
  [661, 'HistoryEventEncodingDefaultBinary'],
  [662, 'HistoryReadRequest'],
  [663, 'HistoryReadRequestEncodingDefaultXml'],
  [664, 'HistoryReadRequestEncodingDefaultBinary'],
  [665, 'HistoryReadResponse'],
  [666, 'HistoryReadResponseEncodingDefaultXml'],
  [667, 'HistoryReadResponseEncodingDefaultBinary'],
  [668, 'WriteValue'],
  [669, 'WriteValueEncodingDefaultXml'],
  [670, 'WriteValueEncodingDefaultBinary'],
  [671, 'WriteRequest'],
  [672, 'WriteRequestEncodingDefaultXml'],
  [673, 'WriteRequestEncodingDefaultBinary'],
  [674, 'WriteResponse'],
  [675, 'WriteResponseEncodingDefaultXml'],
  [676, 'WriteResponseEncodingDefaultBinary'],
  [677, 'HistoryUpdateDetails'],
  [678, 'HistoryUpdateDetailsEncodingDefaultXml'],
  [679, 'HistoryUpdateDetailsEncodingDefaultBinary'],
  [680, 'UpdateDataDetails'],
  [681, 'UpdateDataDetailsEncodingDefaultXml'],
  [682, 'UpdateDataDetailsEncodingDefaultBinary'],
  [683, 'UpdateEventDetails'],
  [684, 'UpdateEventDetailsEncodingDefaultXml'],
  [685, 'UpdateEventDetailsEncodingDefaultBinary'],
  [686, 'DeleteRawModifiedDetails'],
  [687, 'DeleteRawModifiedDetailsEncodingDefaultXml'],
  [688, 'DeleteRawModifiedDetailsEncodingDefaultBinary'],
  [689, 'DeleteAtTimeDetails'],
  [690, 'DeleteAtTimeDetailsEncodingDefaultXml'],
  [691, 'DeleteAtTimeDetailsEncodingDefaultBinary'],
  [692, 'DeleteEventDetails'],
  [693, 'DeleteEventDetailsEncodingDefaultXml'],
  [694, 'DeleteEventDetailsEncodingDefaultBinary'],
  [695, 'HistoryUpdateResult'],
  [696, 'HistoryUpdateResultEncodingDefaultXml'],
  [697, 'HistoryUpdateResultEncodingDefaultBinary'],
  [698, 'HistoryUpdateRequest'],
  [699, 'HistoryUpdateRequestEncodingDefaultXml'],
  [700, 'HistoryUpdateRequestEncodingDefaultBinary'],
  [701, 'HistoryUpdateResponse'],
  [702, 'HistoryUpdateResponseEncodingDefaultXml'],
  [703, 'HistoryUpdateResponseEncodingDefaultBinary'],
  [704, 'CallMethodRequest'],
  [705, 'CallMethodRequestEncodingDefaultXml'],
  [706, 'CallMethodRequestEncodingDefaultBinary'],
  [707, 'CallMethodResult'],
  [708, 'CallMethodResultEncodingDefaultXml'],
  [709, 'CallMethodResultEncodingDefaultBinary'],
  [710, 'CallRequest'],
  [711, 'CallRequestEncodingDefaultXml'],
  [712, 'CallRequestEncodingDefaultBinary'],
  [713, 'CallResponse'],
  [714, 'CallResponseEncodingDefaultXml'],
  [715, 'CallResponseEncodingDefaultBinary'],
  [716, 'MonitoringMode'],
  [717, 'DataChangeTrigger'],
  [718, 'DeadbandType'],
  [719, 'MonitoringFilter'],
  [720, 'MonitoringFilterEncodingDefaultXml'],
  [721, 'MonitoringFilterEncodingDefaultBinary'],
  [722, 'DataChangeFilter'],
  [723, 'DataChangeFilterEncodingDefaultXml'],
  [724, 'DataChangeFilterEncodingDefaultBinary'],
  [725, 'EventFilter'],
  [726, 'EventFilterEncodingDefaultXml'],
  [727, 'EventFilterEncodingDefaultBinary'],
  [728, 'AggregateFilter'],
  [729, 'AggregateFilterEncodingDefaultXml'],
  [730, 'AggregateFilterEncodingDefaultBinary'],
  [731, 'MonitoringFilterResult'],
  [732, 'MonitoringFilterResultEncodingDefaultXml'],
  [733, 'MonitoringFilterResultEncodingDefaultBinary'],
  [734, 'EventFilterResult'],
  [735, 'EventFilterResultEncodingDefaultXml'],
  [736, 'EventFilterResultEncodingDefaultBinary'],
  [737, 'AggregateFilterResult'],
  [738, 'AggregateFilterResultEncodingDefaultXml'],
  [739, 'AggregateFilterResultEncodingDefaultBinary'],
  [740, 'MonitoringParameters'],
  [741, 'MonitoringParametersEncodingDefaultXml'],
  [742, 'MonitoringParametersEncodingDefaultBinary'],
  [743, 'MonitoredItemCreateRequest'],
  [744, 'MonitoredItemCreateRequestEncodingDefaultXml'],
  [745, 'MonitoredItemCreateRequestEncodingDefaultBinary'],
  [746, 'MonitoredItemCreateResult'],
  [747, 'MonitoredItemCreateResultEncodingDefaultXml'],
  [748, 'MonitoredItemCreateResultEncodingDefaultBinary'],
  [749, 'CreateMonitoredItemsRequest'],
  [750, 'CreateMonitoredItemsRequestEncodingDefaultXml'],
  [751, 'CreateMonitoredItemsRequestEncodingDefaultBinary'],
  [752, 'CreateMonitoredItemsResponse'],
  [753, 'CreateMonitoredItemsResponseEncodingDefaultXml'],
  [754, 'CreateMonitoredItemsResponseEncodingDefaultBinary'],
  [755, 'MonitoredItemModifyRequest'],
  [756, 'MonitoredItemModifyRequestEncodingDefaultXml'],
  [757, 'MonitoredItemModifyRequestEncodingDefaultBinary'],
  [758, 'MonitoredItemModifyResult'],
  [759, 'MonitoredItemModifyResultEncodingDefaultXml'],
  [760, 'MonitoredItemModifyResultEncodingDefaultBinary'],
  [761, 'ModifyMonitoredItemsRequest'],
  [762, 'ModifyMonitoredItemsRequestEncodingDefaultXml'],
  [763, 'ModifyMonitoredItemsRequestEncodingDefaultBinary'],
  [764, 'ModifyMonitoredItemsResponse'],
  [765, 'ModifyMonitoredItemsResponseEncodingDefaultXml'],
  [766, 'ModifyMonitoredItemsResponseEncodingDefaultBinary'],
  [767, 'SetMonitoringModeRequest'],
  [768, 'SetMonitoringModeRequestEncodingDefaultXml'],
  [769, 'SetMonitoringModeRequestEncodingDefaultBinary'],
  [770, 'SetMonitoringModeResponse'],
  [771, 'SetMonitoringModeResponseEncodingDefaultXml'],
  [772, 'SetMonitoringModeResponseEncodingDefaultBinary'],
  [773, 'SetTriggeringRequest'],
  [774, 'SetTriggeringRequestEncodingDefaultXml'],
  [775, 'SetTriggeringRequestEncodingDefaultBinary'],
  [776, 'SetTriggeringResponse'],
  [777, 'SetTriggeringResponseEncodingDefaultXml'],
  [778, 'SetTriggeringResponseEncodingDefaultBinary'],
  [779, 'DeleteMonitoredItemsRequest'],
  [780, 'DeleteMonitoredItemsRequestEncodingDefaultXml'],
  [781, 'DeleteMonitoredItemsRequestEncodingDefaultBinary'],
  [782, 'DeleteMonitoredItemsResponse'],
  [783, 'DeleteMonitoredItemsResponseEncodingDefaultXml'],
  [784, 'DeleteMonitoredItemsResponseEncodingDefaultBinary'],
  [785, 'CreateSubscriptionRequest'],
  [786, 'CreateSubscriptionRequestEncodingDefaultXml'],
  [787, 'CreateSubscriptionRequestEncodingDefaultBinary'],
  [788, 'CreateSubscriptionResponse'],
  [789, 'CreateSubscriptionResponseEncodingDefaultXml'],
  [790, 'CreateSubscriptionResponseEncodingDefaultBinary'],
  [791, 'ModifySubscriptionRequest'],
  [792, 'ModifySubscriptionRequestEncodingDefaultXml'],
  [793, 'ModifySubscriptionRequestEncodingDefaultBinary'],
  [794, 'ModifySubscriptionResponse'],
  [795, 'ModifySubscriptionResponseEncodingDefaultXml'],
  [796, 'ModifySubscriptionResponseEncodingDefaultBinary'],
  [797, 'SetPublishingModeRequest'],
  [798, 'SetPublishingModeRequestEncodingDefaultXml'],
  [799, 'SetPublishingModeRequestEncodingDefaultBinary'],
  [800, 'SetPublishingModeResponse'],
  [801, 'SetPublishingModeResponseEncodingDefaultXml'],
  [802, 'SetPublishingModeResponseEncodingDefaultBinary'],
  [803, 'NotificationMessage'],
  [804, 'NotificationMessageEncodingDefaultXml'],
  [805, 'NotificationMessageEncodingDefaultBinary'],
  [806, 'MonitoredItemNotification'],
  [807, 'MonitoredItemNotificationEncodingDefaultXml'],
  [808, 'MonitoredItemNotificationEncodingDefaultBinary'],
  [809, 'DataChangeNotification'],
  [810, 'DataChangeNotificationEncodingDefaultXml'],
  [811, 'DataChangeNotificationEncodingDefaultBinary'],
  [818, 'StatusChangeNotification'],
  [819, 'StatusChangeNotificationEncodingDefaultXml'],
  [820, 'StatusChangeNotificationEncodingDefaultBinary'],
  [821, 'SubscriptionAcknowledgement'],
  [822, 'SubscriptionAcknowledgementEncodingDefaultXml'],
  [823, 'SubscriptionAcknowledgementEncodingDefaultBinary'],
  [824, 'PublishRequest'],
  [825, 'PublishRequestEncodingDefaultXml'],
  [826, 'PublishRequestEncodingDefaultBinary'],
  [827, 'PublishResponse'],
  [828, 'PublishResponseEncodingDefaultXml'],
  [829, 'PublishResponseEncodingDefaultBinary'],
  [830, 'RepublishRequest'],
  [831, 'RepublishRequestEncodingDefaultXml'],
  [832, 'RepublishRequestEncodingDefaultBinary'],
  [833, 'RepublishResponse'],
  [834, 'RepublishResponseEncodingDefaultXml'],
  [835, 'RepublishResponseEncodingDefaultBinary'],
  [836, 'TransferResult'],
  [837, 'TransferResultEncodingDefaultXml'],
  [838, 'TransferResultEncodingDefaultBinary'],
  [839, 'TransferSubscriptionsRequest'],
  [840, 'TransferSubscriptionsRequestEncodingDefaultXml'],
  [841, 'TransferSubscriptionsRequestEncodingDefaultBinary'],
  [842, 'TransferSubscriptionsResponse'],
  [843, 'TransferSubscriptionsResponseEncodingDefaultXml'],
  [844, 'TransferSubscriptionsResponseEncodingDefaultBinary'],
  [845, 'DeleteSubscriptionsRequest'],
  [846, 'DeleteSubscriptionsRequestEncodingDefaultXml'],
  [847, 'DeleteSubscriptionsRequestEncodingDefaultBinary'],
  [848, 'DeleteSubscriptionsResponse'],
  [849, 'DeleteSubscriptionsResponseEncodingDefaultXml'],
  [850, 'DeleteSubscriptionsResponseEncodingDefaultBinary'],
  [851, 'RedundancySupport'],
  [852, 'ServerState'],
  [853, 'RedundantServerDataType'],
  [854, 'RedundantServerDataTypeEncodingDefaultXml'],
  [855, 'RedundantServerDataTypeEncodingDefaultBinary'],
  [856, 'SamplingIntervalDiagnosticsDataType'],
  [857, 'SamplingIntervalDiagnosticsDataTypeEncodingDefaultXml'],
  [858, 'SamplingIntervalDiagnosticsDataTypeEncodingDefaultBinary'],
  [859, 'ServerDiagnosticsSummaryDataType'],
  [860, 'ServerDiagnosticsSummaryDataTypeEncodingDefaultXml'],
  [861, 'ServerDiagnosticsSummaryDataTypeEncodingDefaultBinary'],
  [862, 'ServerStatusDataType'],
  [863, 'ServerStatusDataTypeEncodingDefaultXml'],
  [864, 'ServerStatusDataTypeEncodingDefaultBinary'],
  [865, 'SessionDiagnosticsDataType'],
  [866, 'SessionDiagnosticsDataTypeEncodingDefaultXml'],
  [867, 'SessionDiagnosticsDataTypeEncodingDefaultBinary'],
  [868, 'SessionSecurityDiagnosticsDataType'],
  [869, 'SessionSecurityDiagnosticsDataTypeEncodingDefaultXml'],
  [870, 'SessionSecurityDiagnosticsDataTypeEncodingDefaultBinary'],
  [871, 'ServiceCounterDataType'],
  [872, 'ServiceCounterDataTypeEncodingDefaultXml'],
  [873, 'ServiceCounterDataTypeEncodingDefaultBinary'],
  [874, 'SubscriptionDiagnosticsDataType'],
  [875, 'SubscriptionDiagnosticsDataTypeEncodingDefaultXml'],
  [876, 'SubscriptionDiagnosticsDataTypeEncodingDefaultBinary'],
  [877, 'ModelChangeStructureDataType'],
  [878, 'ModelChangeStructureDataTypeEncodingDefaultXml'],
  [879, 'ModelChangeStructureDataTypeEncodingDefaultBinary'],
  [884, 'Range'],
  [885, 'RangeEncodingDefaultXml'],
  [886, 'RangeEncodingDefaultBinary'],
  [887, 'EUInformation'],
  [888, 'EUInformationEncodingDefaultXml'],
  [889, 'EUInformationEncodingDefaultBinary'],
  [890, 'ExceptionDeviationFormat'],
  [891, 'Annotation'],
  [892, 'AnnotationEncodingDefaultXml'],
  [893, 'AnnotationEncodingDefaultBinary'],
  [894, 'ProgramDiagnosticDataType'],
  [895, 'ProgramDiagnosticDataTypeEncodingDefaultXml'],
  [896, 'ProgramDiagnosticDataTypeEncodingDefaultBinary'],
  [897, 'SemanticChangeStructureDataType'],
  [898, 'SemanticChangeStructureDataTypeEncodingDefaultXml'],
  [899, 'SemanticChangeStructureDataTypeEncodingDefaultBinary'],
  [914, 'EventNotificationList'],
  [915, 'EventNotificationListEncodingDefaultXml'],
  [916, 'EventNotificationListEncodingDefaultBinary'],
  [917, 'EventFieldList'],
  [918, 'EventFieldListEncodingDefaultXml'],
  [919, 'EventFieldListEncodingDefaultBinary'],
  [920, 'HistoryEventFieldList'],
  [921, 'HistoryEventFieldListEncodingDefaultXml'],
  [922, 'HistoryEventFieldListEncodingDefaultBinary'],
  [938, 'IssuedIdentityToken'],
  [939, 'IssuedIdentityTokenEncodingDefaultXml'],
  [940, 'IssuedIdentityTokenEncodingDefaultBinary'],
  [945, 'NotificationData'],
  [946, 'NotificationDataEncodingDefaultXml'],
  [947, 'NotificationDataEncodingDefaultBinary'],
  [948, 'AggregateConfiguration'],
  [949, 'AggregateConfigurationEncodingDefaultXml'],
  [950, 'AggregateConfigurationEncodingDefaultBinary']
])

export const mapNameToId = new Map([
  ['Boolean', 1],
  ['SByte', 2],
  ['Byte', 3],
  ['Int16', 4],
  ['UInt16', 5],
  ['Int32', 6],
  ['UInt32', 7],
  ['Int64', 8],
  ['UInt64', 9],
  ['Float', 10],
  ['Double', 11],
  ['String', 12],
  ['DateTime', 13],
  ['Guid', 14],
  ['ByteString', 15],
  ['XmlElement', 16],
  ['NodeId', 17],
  ['ExpandedNodeId', 18],
  ['StatusCode', 19],
  ['QualifiedName', 20],
  ['LocalizedText', 21],
  ['Structure', 22],
  ['DataValue', 23],
  ['BaseDataType', 24],
  ['DiagnosticInfo', 25],
  ['Number', 26],
  ['Integer', 27],
  ['UInteger', 28],
  ['Enumeration', 29],
  ['Image', 30],
  ['References', 31],
  ['NonHierarchicalReferences', 32],
  ['HierarchicalReferences', 33],
  ['HasChild', 34],
  ['Organizes', 35],
  ['HasEventSource', 36],
  ['HasModellingRule', 37],
  ['HasEncoding', 38],
  ['HasDescription', 39],
  ['HasTypeDefinition', 40],
  ['GeneratesEvent', 41],
  ['Aggregates', 44],
  ['HasSubtype', 45],
  ['HasProperty', 46],
  ['HasComponent', 47],
  ['HasNotifier', 48],
  ['HasOrderedComponent', 49],
  ['Decimal', 50],
  ['FromState', 51],
  ['ToState', 52],
  ['HasCause', 53],
  ['HasEffect', 54],
  ['HasHistoricalConfiguration', 56],
  ['BaseObjectType', 58],
  ['FolderType', 61],
  ['BaseVariableType', 62],
  ['BaseDataVariableType', 63],
  ['PropertyType', 68],
  ['DataTypeDescriptionType', 69],
  ['DataTypeDictionaryType', 72],
  ['DataTypeSystemType', 75],
  ['DataTypeEncodingType', 76],
  ['ModellingRuleType', 77],
  ['ModellingRuleMandatory', 78],
  ['ModellingRuleOptional', 80],
  ['ModellingRuleExposesItsArray', 83],
  ['RootFolder', 84],
  ['ObjectsFolder', 85],
  ['TypesFolder', 86],
  ['ViewsFolder', 87],
  ['ObjectTypesFolder', 88],
  ['VariableTypesFolder', 89],
  ['DataTypesFolder', 90],
  ['ReferenceTypesFolder', 91],
  ['XmlSchemaTypeSystem', 92],
  ['OPCBinarySchemaTypeSystem', 93],
  ['PermissionType', 94],
  ['AccessRestrictionType', 95],
  ['RolePermissionType', 96],
  ['DataTypeDefinition', 97],
  ['StructureType', 98],
  ['StructureDefinition', 99],
  ['EnumDefinition', 100],
  ['StructureField', 101],
  ['EnumField', 102],
  ['DataTypeDescriptionTypeDataTypeVersion', 104],
  ['DataTypeDescriptionTypeDictionaryFragment', 105],
  ['DataTypeDictionaryTypeDataTypeVersion', 106],
  ['DataTypeDictionaryTypeNamespaceUri', 107],
  ['ModellingRuleTypeNamingRule', 111],
  ['ModellingRuleMandatoryNamingRule', 112],
  ['ModellingRuleOptionalNamingRule', 113],
  ['ModellingRuleExposesItsArrayNamingRule', 114],
  ['HasSubStateMachine', 117],
  ['NamingRuleType', 120],
  ['DataTypeDefinitionEncodingDefaultBinary', 121],
  ['StructureDefinitionEncodingDefaultBinary', 122],
  ['EnumDefinitionEncodingDefaultBinary', 123],
  ['DataSetMetaDataTypeEncodingDefaultBinary', 124],
  ['DataTypeDescriptionEncodingDefaultBinary', 125],
  ['StructureDescriptionEncodingDefaultBinary', 126],
  ['EnumDescriptionEncodingDefaultBinary', 127],
  ['RolePermissionTypeEncodingDefaultBinary', 128],
  ['HasArgumentDescription', 129],
  ['HasOptionalInputArgumentDescription', 131],
  ['IdType', 256],
  ['NodeClass', 257],
  ['Node', 258],
  ['NodeEncodingDefaultXml', 259],
  ['NodeEncodingDefaultBinary', 260],
  ['ObjectNode', 261],
  ['ObjectNodeEncodingDefaultXml', 262],
  ['ObjectNodeEncodingDefaultBinary', 263],
  ['ObjectTypeNode', 264],
  ['ObjectTypeNodeEncodingDefaultXml', 265],
  ['ObjectTypeNodeEncodingDefaultBinary', 266],
  ['VariableNode', 267],
  ['VariableNodeEncodingDefaultXml', 268],
  ['VariableNodeEncodingDefaultBinary', 269],
  ['VariableTypeNode', 270],
  ['VariableTypeNodeEncodingDefaultXml', 271],
  ['VariableTypeNodeEncodingDefaultBinary', 272],
  ['ReferenceTypeNode', 273],
  ['ReferenceTypeNodeEncodingDefaultXml', 274],
  ['ReferenceTypeNodeEncodingDefaultBinary', 275],
  ['MethodNode', 276],
  ['MethodNodeEncodingDefaultXml', 277],
  ['MethodNodeEncodingDefaultBinary', 278],
  ['ViewNode', 279],
  ['ViewNodeEncodingDefaultXml', 280],
  ['ViewNodeEncodingDefaultBinary', 281],
  ['DataTypeNode', 282],
  ['DataTypeNodeEncodingDefaultXml', 283],
  ['DataTypeNodeEncodingDefaultBinary', 284],
  ['ReferenceNode', 285],
  ['ReferenceNodeEncodingDefaultXml', 286],
  ['ReferenceNodeEncodingDefaultBinary', 287],
  ['IntegerId', 288],
  ['Counter', 289],
  ['Duration', 290],
  ['NumericRange', 291],
  ['Time', 292],
  ['Date', 293],
  ['UtcTime', 294],
  ['LocaleId', 295],
  ['Argument', 296],
  ['ArgumentEncodingDefaultXml', 297],
  ['ArgumentEncodingDefaultBinary', 298],
  ['StatusResult', 299],
  ['StatusResultEncodingDefaultXml', 300],
  ['StatusResultEncodingDefaultBinary', 301],
  ['MessageSecurityMode', 302],
  ['UserTokenType', 303],
  ['UserTokenPolicy', 304],
  ['UserTokenPolicyEncodingDefaultXml', 305],
  ['UserTokenPolicyEncodingDefaultBinary', 306],
  ['ApplicationType', 307],
  ['ApplicationDescription', 308],
  ['ApplicationDescriptionEncodingDefaultXml', 309],
  ['ApplicationDescriptionEncodingDefaultBinary', 310],
  ['ApplicationInstanceCertificate', 311],
  ['EndpointDescription', 312],
  ['EndpointDescriptionEncodingDefaultXml', 313],
  ['EndpointDescriptionEncodingDefaultBinary', 314],
  ['SecurityTokenRequestType', 315],
  ['UserIdentityToken', 316],
  ['UserIdentityTokenEncodingDefaultXml', 317],
  ['UserIdentityTokenEncodingDefaultBinary', 318],
  ['AnonymousIdentityToken', 319],
  ['AnonymousIdentityTokenEncodingDefaultXml', 320],
  ['AnonymousIdentityTokenEncodingDefaultBinary', 321],
  ['UserNameIdentityToken', 322],
  ['UserNameIdentityTokenEncodingDefaultXml', 323],
  ['UserNameIdentityTokenEncodingDefaultBinary', 324],
  ['X509IdentityToken', 325],
  ['X509IdentityTokenEncodingDefaultXml', 326],
  ['X509IdentityTokenEncodingDefaultBinary', 327],
  ['EndpointConfiguration', 331],
  ['EndpointConfigurationEncodingDefaultXml', 332],
  ['EndpointConfigurationEncodingDefaultBinary', 333],
  ['BuildInfo', 338],
  ['BuildInfoEncodingDefaultXml', 339],
  ['BuildInfoEncodingDefaultBinary', 340],
  ['SignedSoftwareCertificate', 344],
  ['SignedSoftwareCertificateEncodingDefaultXml', 345],
  ['SignedSoftwareCertificateEncodingDefaultBinary', 346],
  ['AttributeWriteMask', 347],
  ['NodeAttributesMask', 348],
  ['NodeAttributes', 349],
  ['NodeAttributesEncodingDefaultXml', 350],
  ['NodeAttributesEncodingDefaultBinary', 351],
  ['ObjectAttributes', 352],
  ['ObjectAttributesEncodingDefaultXml', 353],
  ['ObjectAttributesEncodingDefaultBinary', 354],
  ['VariableAttributes', 355],
  ['VariableAttributesEncodingDefaultXml', 356],
  ['VariableAttributesEncodingDefaultBinary', 357],
  ['MethodAttributes', 358],
  ['MethodAttributesEncodingDefaultXml', 359],
  ['MethodAttributesEncodingDefaultBinary', 360],
  ['ObjectTypeAttributes', 361],
  ['ObjectTypeAttributesEncodingDefaultXml', 362],
  ['ObjectTypeAttributesEncodingDefaultBinary', 363],
  ['VariableTypeAttributes', 364],
  ['VariableTypeAttributesEncodingDefaultXml', 365],
  ['VariableTypeAttributesEncodingDefaultBinary', 366],
  ['ReferenceTypeAttributes', 367],
  ['ReferenceTypeAttributesEncodingDefaultXml', 368],
  ['ReferenceTypeAttributesEncodingDefaultBinary', 369],
  ['DataTypeAttributes', 370],
  ['DataTypeAttributesEncodingDefaultXml', 371],
  ['DataTypeAttributesEncodingDefaultBinary', 372],
  ['ViewAttributes', 373],
  ['ViewAttributesEncodingDefaultXml', 374],
  ['ViewAttributesEncodingDefaultBinary', 375],
  ['AddNodesItem', 376],
  ['AddNodesItemEncodingDefaultXml', 377],
  ['AddNodesItemEncodingDefaultBinary', 378],
  ['AddReferencesItem', 379],
  ['AddReferencesItemEncodingDefaultXml', 380],
  ['AddReferencesItemEncodingDefaultBinary', 381],
  ['DeleteNodesItem', 382],
  ['DeleteNodesItemEncodingDefaultXml', 383],
  ['DeleteNodesItemEncodingDefaultBinary', 384],
  ['DeleteReferencesItem', 385],
  ['DeleteReferencesItemEncodingDefaultXml', 386],
  ['DeleteReferencesItemEncodingDefaultBinary', 387],
  ['SessionAuthenticationToken', 388],
  ['RequestHeader', 389],
  ['RequestHeaderEncodingDefaultXml', 390],
  ['RequestHeaderEncodingDefaultBinary', 391],
  ['ResponseHeader', 392],
  ['ResponseHeaderEncodingDefaultXml', 393],
  ['ResponseHeaderEncodingDefaultBinary', 394],
  ['ServiceFault', 395],
  ['ServiceFaultEncodingDefaultXml', 396],
  ['ServiceFaultEncodingDefaultBinary', 397],
  ['FindServersRequest', 420],
  ['FindServersRequestEncodingDefaultXml', 421],
  ['FindServersRequestEncodingDefaultBinary', 422],
  ['FindServersResponse', 423],
  ['FindServersResponseEncodingDefaultXml', 424],
  ['FindServersResponseEncodingDefaultBinary', 425],
  ['GetEndpointsRequest', 426],
  ['GetEndpointsRequestEncodingDefaultXml', 427],
  ['GetEndpointsRequestEncodingDefaultBinary', 428],
  ['GetEndpointsResponse', 429],
  ['GetEndpointsResponseEncodingDefaultXml', 430],
  ['GetEndpointsResponseEncodingDefaultBinary', 431],
  ['RegisteredServer', 432],
  ['RegisteredServerEncodingDefaultXml', 433],
  ['RegisteredServerEncodingDefaultBinary', 434],
  ['RegisterServerRequest', 435],
  ['RegisterServerRequestEncodingDefaultXml', 436],
  ['RegisterServerRequestEncodingDefaultBinary', 437],
  ['RegisterServerResponse', 438],
  ['RegisterServerResponseEncodingDefaultXml', 439],
  ['RegisterServerResponseEncodingDefaultBinary', 440],
  ['ChannelSecurityToken', 441],
  ['ChannelSecurityTokenEncodingDefaultXml', 442],
  ['ChannelSecurityTokenEncodingDefaultBinary', 443],
  ['OpenSecureChannelRequest', 444],
  ['OpenSecureChannelRequestEncodingDefaultXml', 445],
  ['OpenSecureChannelRequestEncodingDefaultBinary', 446],
  ['OpenSecureChannelResponse', 447],
  ['OpenSecureChannelResponseEncodingDefaultXml', 448],
  ['OpenSecureChannelResponseEncodingDefaultBinary', 449],
  ['CloseSecureChannelRequest', 450],
  ['CloseSecureChannelRequestEncodingDefaultXml', 451],
  ['CloseSecureChannelRequestEncodingDefaultBinary', 452],
  ['CloseSecureChannelResponse', 453],
  ['CloseSecureChannelResponseEncodingDefaultXml', 454],
  ['CloseSecureChannelResponseEncodingDefaultBinary', 455],
  ['SignatureData', 456],
  ['SignatureDataEncodingDefaultXml', 457],
  ['SignatureDataEncodingDefaultBinary', 458],
  ['CreateSessionRequest', 459],
  ['CreateSessionRequestEncodingDefaultXml', 460],
  ['CreateSessionRequestEncodingDefaultBinary', 461],
  ['CreateSessionResponse', 462],
  ['CreateSessionResponseEncodingDefaultXml', 463],
  ['CreateSessionResponseEncodingDefaultBinary', 464],
  ['ActivateSessionRequest', 465],
  ['ActivateSessionRequestEncodingDefaultXml', 466],
  ['ActivateSessionRequestEncodingDefaultBinary', 467],
  ['ActivateSessionResponse', 468],
  ['ActivateSessionResponseEncodingDefaultXml', 469],
  ['ActivateSessionResponseEncodingDefaultBinary', 470],
  ['CloseSessionRequest', 471],
  ['CloseSessionRequestEncodingDefaultXml', 472],
  ['CloseSessionRequestEncodingDefaultBinary', 473],
  ['CloseSessionResponse', 474],
  ['CloseSessionResponseEncodingDefaultXml', 475],
  ['CloseSessionResponseEncodingDefaultBinary', 476],
  ['CancelRequest', 477],
  ['CancelRequestEncodingDefaultXml', 478],
  ['CancelRequestEncodingDefaultBinary', 479],
  ['CancelResponse', 480],
  ['CancelResponseEncodingDefaultXml', 481],
  ['CancelResponseEncodingDefaultBinary', 482],
  ['AddNodesResult', 483],
  ['AddNodesResultEncodingDefaultXml', 484],
  ['AddNodesResultEncodingDefaultBinary', 485],
  ['AddNodesRequest', 486],
  ['AddNodesRequestEncodingDefaultXml', 487],
  ['AddNodesRequestEncodingDefaultBinary', 488],
  ['AddNodesResponse', 489],
  ['AddNodesResponseEncodingDefaultXml', 490],
  ['AddNodesResponseEncodingDefaultBinary', 491],
  ['AddReferencesRequest', 492],
  ['AddReferencesRequestEncodingDefaultXml', 493],
  ['AddReferencesRequestEncodingDefaultBinary', 494],
  ['AddReferencesResponse', 495],
  ['AddReferencesResponseEncodingDefaultXml', 496],
  ['AddReferencesResponseEncodingDefaultBinary', 497],
  ['DeleteNodesRequest', 498],
  ['DeleteNodesRequestEncodingDefaultXml', 499],
  ['DeleteNodesRequestEncodingDefaultBinary', 500],
  ['DeleteNodesResponse', 501],
  ['DeleteNodesResponseEncodingDefaultXml', 502],
  ['DeleteNodesResponseEncodingDefaultBinary', 503],
  ['DeleteReferencesRequest', 504],
  ['DeleteReferencesRequestEncodingDefaultXml', 505],
  ['DeleteReferencesRequestEncodingDefaultBinary', 506],
  ['DeleteReferencesResponse', 507],
  ['DeleteReferencesResponseEncodingDefaultXml', 508],
  ['DeleteReferencesResponseEncodingDefaultBinary', 509],
  ['BrowseDirection', 510],
  ['ViewDescription', 511],
  ['ViewDescriptionEncodingDefaultXml', 512],
  ['ViewDescriptionEncodingDefaultBinary', 513],
  ['BrowseDescription', 514],
  ['BrowseDescriptionEncodingDefaultXml', 515],
  ['BrowseDescriptionEncodingDefaultBinary', 516],
  ['BrowseResultMask', 517],
  ['ReferenceDescription', 518],
  ['ReferenceDescriptionEncodingDefaultXml', 519],
  ['ReferenceDescriptionEncodingDefaultBinary', 520],
  ['ContinuationPoint', 521],
  ['BrowseResult', 522],
  ['BrowseResultEncodingDefaultXml', 523],
  ['BrowseResultEncodingDefaultBinary', 524],
  ['BrowseRequest', 525],
  ['BrowseRequestEncodingDefaultXml', 526],
  ['BrowseRequestEncodingDefaultBinary', 527],
  ['BrowseResponse', 528],
  ['BrowseResponseEncodingDefaultXml', 529],
  ['BrowseResponseEncodingDefaultBinary', 530],
  ['BrowseNextRequest', 531],
  ['BrowseNextRequestEncodingDefaultXml', 532],
  ['BrowseNextRequestEncodingDefaultBinary', 533],
  ['BrowseNextResponse', 534],
  ['BrowseNextResponseEncodingDefaultXml', 535],
  ['BrowseNextResponseEncodingDefaultBinary', 536],
  ['RelativePathElement', 537],
  ['RelativePathElementEncodingDefaultXml', 538],
  ['RelativePathElementEncodingDefaultBinary', 539],
  ['RelativePath', 540],
  ['RelativePathEncodingDefaultXml', 541],
  ['RelativePathEncodingDefaultBinary', 542],
  ['BrowsePath', 543],
  ['BrowsePathEncodingDefaultXml', 544],
  ['BrowsePathEncodingDefaultBinary', 545],
  ['BrowsePathTarget', 546],
  ['BrowsePathTargetEncodingDefaultXml', 547],
  ['BrowsePathTargetEncodingDefaultBinary', 548],
  ['BrowsePathResult', 549],
  ['BrowsePathResultEncodingDefaultXml', 550],
  ['BrowsePathResultEncodingDefaultBinary', 551],
  ['TranslateBrowsePathsToNodeIdsRequest', 552],
  ['TranslateBrowsePathsToNodeIdsRequestEncodingDefaultXml', 553],
  ['TranslateBrowsePathsToNodeIdsRequestEncodingDefaultBinary', 554],
  ['TranslateBrowsePathsToNodeIdsResponse', 555],
  ['TranslateBrowsePathsToNodeIdsResponseEncodingDefaultXml', 556],
  ['TranslateBrowsePathsToNodeIdsResponseEncodingDefaultBinary', 557],
  ['RegisterNodesRequest', 558],
  ['RegisterNodesRequestEncodingDefaultXml', 559],
  ['RegisterNodesRequestEncodingDefaultBinary', 560],
  ['RegisterNodesResponse', 561],
  ['RegisterNodesResponseEncodingDefaultXml', 562],
  ['RegisterNodesResponseEncodingDefaultBinary', 563],
  ['UnregisterNodesRequest', 564],
  ['UnregisterNodesRequestEncodingDefaultXml', 565],
  ['UnregisterNodesRequestEncodingDefaultBinary', 566],
  ['UnregisterNodesResponse', 567],
  ['UnregisterNodesResponseEncodingDefaultXml', 568],
  ['UnregisterNodesResponseEncodingDefaultBinary', 569],
  ['QueryDataDescription', 570],
  ['QueryDataDescriptionEncodingDefaultXml', 571],
  ['QueryDataDescriptionEncodingDefaultBinary', 572],
  ['NodeTypeDescription', 573],
  ['NodeTypeDescriptionEncodingDefaultXml', 574],
  ['NodeTypeDescriptionEncodingDefaultBinary', 575],
  ['FilterOperator', 576],
  ['QueryDataSet', 577],
  ['QueryDataSetEncodingDefaultXml', 578],
  ['QueryDataSetEncodingDefaultBinary', 579],
  ['NodeReference', 580],
  ['NodeReferenceEncodingDefaultXml', 581],
  ['NodeReferenceEncodingDefaultBinary', 582],
  ['ContentFilterElement', 583],
  ['ContentFilterElementEncodingDefaultXml', 584],
  ['ContentFilterElementEncodingDefaultBinary', 585],
  ['ContentFilter', 586],
  ['ContentFilterEncodingDefaultXml', 587],
  ['ContentFilterEncodingDefaultBinary', 588],
  ['FilterOperand', 589],
  ['FilterOperandEncodingDefaultXml', 590],
  ['FilterOperandEncodingDefaultBinary', 591],
  ['ElementOperand', 592],
  ['ElementOperandEncodingDefaultXml', 593],
  ['ElementOperandEncodingDefaultBinary', 594],
  ['LiteralOperand', 595],
  ['LiteralOperandEncodingDefaultXml', 596],
  ['LiteralOperandEncodingDefaultBinary', 597],
  ['AttributeOperand', 598],
  ['AttributeOperandEncodingDefaultXml', 599],
  ['AttributeOperandEncodingDefaultBinary', 600],
  ['SimpleAttributeOperand', 601],
  ['SimpleAttributeOperandEncodingDefaultXml', 602],
  ['SimpleAttributeOperandEncodingDefaultBinary', 603],
  ['ContentFilterElementResult', 604],
  ['ContentFilterElementResultEncodingDefaultXml', 605],
  ['ContentFilterElementResultEncodingDefaultBinary', 606],
  ['ContentFilterResult', 607],
  ['ContentFilterResultEncodingDefaultXml', 608],
  ['ContentFilterResultEncodingDefaultBinary', 609],
  ['ParsingResult', 610],
  ['ParsingResultEncodingDefaultXml', 611],
  ['ParsingResultEncodingDefaultBinary', 612],
  ['QueryFirstRequest', 613],
  ['QueryFirstRequestEncodingDefaultXml', 614],
  ['QueryFirstRequestEncodingDefaultBinary', 615],
  ['QueryFirstResponse', 616],
  ['QueryFirstResponseEncodingDefaultXml', 617],
  ['QueryFirstResponseEncodingDefaultBinary', 618],
  ['QueryNextRequest', 619],
  ['QueryNextRequestEncodingDefaultXml', 620],
  ['QueryNextRequestEncodingDefaultBinary', 621],
  ['QueryNextResponse', 622],
  ['QueryNextResponseEncodingDefaultXml', 623],
  ['QueryNextResponseEncodingDefaultBinary', 624],
  ['TimestampsToReturn', 625],
  ['ReadValueId', 626],
  ['ReadValueIdEncodingDefaultXml', 627],
  ['ReadValueIdEncodingDefaultBinary', 628],
  ['ReadRequest', 629],
  ['ReadRequestEncodingDefaultXml', 630],
  ['ReadRequestEncodingDefaultBinary', 631],
  ['ReadResponse', 632],
  ['ReadResponseEncodingDefaultXml', 633],
  ['ReadResponseEncodingDefaultBinary', 634],
  ['HistoryReadValueId', 635],
  ['HistoryReadValueIdEncodingDefaultXml', 636],
  ['HistoryReadValueIdEncodingDefaultBinary', 637],
  ['HistoryReadResult', 638],
  ['HistoryReadResultEncodingDefaultXml', 639],
  ['HistoryReadResultEncodingDefaultBinary', 640],
  ['HistoryReadDetails', 641],
  ['HistoryReadDetailsEncodingDefaultXml', 642],
  ['HistoryReadDetailsEncodingDefaultBinary', 643],
  ['ReadEventDetails', 644],
  ['ReadEventDetailsEncodingDefaultXml', 645],
  ['ReadEventDetailsEncodingDefaultBinary', 646],
  ['ReadRawModifiedDetails', 647],
  ['ReadRawModifiedDetailsEncodingDefaultXml', 648],
  ['ReadRawModifiedDetailsEncodingDefaultBinary', 649],
  ['ReadProcessedDetails', 650],
  ['ReadProcessedDetailsEncodingDefaultXml', 651],
  ['ReadProcessedDetailsEncodingDefaultBinary', 652],
  ['ReadAtTimeDetails', 653],
  ['ReadAtTimeDetailsEncodingDefaultXml', 654],
  ['ReadAtTimeDetailsEncodingDefaultBinary', 655],
  ['HistoryData', 656],
  ['HistoryDataEncodingDefaultXml', 657],
  ['HistoryDataEncodingDefaultBinary', 658],
  ['HistoryEvent', 659],
  ['HistoryEventEncodingDefaultXml', 660],
  ['HistoryEventEncodingDefaultBinary', 661],
  ['HistoryReadRequest', 662],
  ['HistoryReadRequestEncodingDefaultXml', 663],
  ['HistoryReadRequestEncodingDefaultBinary', 664],
  ['HistoryReadResponse', 665],
  ['HistoryReadResponseEncodingDefaultXml', 666],
  ['HistoryReadResponseEncodingDefaultBinary', 667],
  ['WriteValue', 668],
  ['WriteValueEncodingDefaultXml', 669],
  ['WriteValueEncodingDefaultBinary', 670],
  ['WriteRequest', 671],
  ['WriteRequestEncodingDefaultXml', 672],
  ['WriteRequestEncodingDefaultBinary', 673],
  ['WriteResponse', 674],
  ['WriteResponseEncodingDefaultXml', 675],
  ['WriteResponseEncodingDefaultBinary', 676],
  ['HistoryUpdateDetails', 677],
  ['HistoryUpdateDetailsEncodingDefaultXml', 678],
  ['HistoryUpdateDetailsEncodingDefaultBinary', 679],
  ['UpdateDataDetails', 680],
  ['UpdateDataDetailsEncodingDefaultXml', 681],
  ['UpdateDataDetailsEncodingDefaultBinary', 682],
  ['UpdateEventDetails', 683],
  ['UpdateEventDetailsEncodingDefaultXml', 684],
  ['UpdateEventDetailsEncodingDefaultBinary', 685],
  ['DeleteRawModifiedDetails', 686],
  ['DeleteRawModifiedDetailsEncodingDefaultXml', 687],
  ['DeleteRawModifiedDetailsEncodingDefaultBinary', 688],
  ['DeleteAtTimeDetails', 689],
  ['DeleteAtTimeDetailsEncodingDefaultXml', 690],
  ['DeleteAtTimeDetailsEncodingDefaultBinary', 691],
  ['DeleteEventDetails', 692],
  ['DeleteEventDetailsEncodingDefaultXml', 693],
  ['DeleteEventDetailsEncodingDefaultBinary', 694],
  ['HistoryUpdateResult', 695],
  ['HistoryUpdateResultEncodingDefaultXml', 696],
  ['HistoryUpdateResultEncodingDefaultBinary', 697],
  ['HistoryUpdateRequest', 698],
  ['HistoryUpdateRequestEncodingDefaultXml', 699],
  ['HistoryUpdateRequestEncodingDefaultBinary', 700],
  ['HistoryUpdateResponse', 701],
  ['HistoryUpdateResponseEncodingDefaultXml', 702],
  ['HistoryUpdateResponseEncodingDefaultBinary', 703],
  ['CallMethodRequest', 704],
  ['CallMethodRequestEncodingDefaultXml', 705],
  ['CallMethodRequestEncodingDefaultBinary', 706],
  ['CallMethodResult', 707],
  ['CallMethodResultEncodingDefaultXml', 708],
  ['CallMethodResultEncodingDefaultBinary', 709],
  ['CallRequest', 710],
  ['CallRequestEncodingDefaultXml', 711],
  ['CallRequestEncodingDefaultBinary', 712],
  ['CallResponse', 713],
  ['CallResponseEncodingDefaultXml', 714],
  ['CallResponseEncodingDefaultBinary', 715],
  ['MonitoringMode', 716],
  ['DataChangeTrigger', 717],
  ['DeadbandType', 718],
  ['MonitoringFilter', 719],
  ['MonitoringFilterEncodingDefaultXml', 720],
  ['MonitoringFilterEncodingDefaultBinary', 721],
  ['DataChangeFilter', 722],
  ['DataChangeFilterEncodingDefaultXml', 723],
  ['DataChangeFilterEncodingDefaultBinary', 724],
  ['EventFilter', 725],
  ['EventFilterEncodingDefaultXml', 726],
  ['EventFilterEncodingDefaultBinary', 727],
  ['AggregateFilter', 728],
  ['AggregateFilterEncodingDefaultXml', 729],
  ['AggregateFilterEncodingDefaultBinary', 730],
  ['MonitoringFilterResult', 731],
  ['MonitoringFilterResultEncodingDefaultXml', 732],
  ['MonitoringFilterResultEncodingDefaultBinary', 733],
  ['EventFilterResult', 734],
  ['EventFilterResultEncodingDefaultXml', 735],
  ['EventFilterResultEncodingDefaultBinary', 736],
  ['AggregateFilterResult', 737],
  ['AggregateFilterResultEncodingDefaultXml', 738],
  ['AggregateFilterResultEncodingDefaultBinary', 739],
  ['MonitoringParameters', 740],
  ['MonitoringParametersEncodingDefaultXml', 741],
  ['MonitoringParametersEncodingDefaultBinary', 742],
  ['MonitoredItemCreateRequest', 743],
  ['MonitoredItemCreateRequestEncodingDefaultXml', 744],
  ['MonitoredItemCreateRequestEncodingDefaultBinary', 745],
  ['MonitoredItemCreateResult', 746],
  ['MonitoredItemCreateResultEncodingDefaultXml', 747],
  ['MonitoredItemCreateResultEncodingDefaultBinary', 748],
  ['CreateMonitoredItemsRequest', 749],
  ['CreateMonitoredItemsRequestEncodingDefaultXml', 750],
  ['CreateMonitoredItemsRequestEncodingDefaultBinary', 751],
  ['CreateMonitoredItemsResponse', 752],
  ['CreateMonitoredItemsResponseEncodingDefaultXml', 753],
  ['CreateMonitoredItemsResponseEncodingDefaultBinary', 754],
  ['MonitoredItemModifyRequest', 755],
  ['MonitoredItemModifyRequestEncodingDefaultXml', 756],
  ['MonitoredItemModifyRequestEncodingDefaultBinary', 757],
  ['MonitoredItemModifyResult', 758],
  ['MonitoredItemModifyResultEncodingDefaultXml', 759],
  ['MonitoredItemModifyResultEncodingDefaultBinary', 760],
  ['ModifyMonitoredItemsRequest', 761],
  ['ModifyMonitoredItemsRequestEncodingDefaultXml', 762],
  ['ModifyMonitoredItemsRequestEncodingDefaultBinary', 763],
  ['ModifyMonitoredItemsResponse', 764],
  ['ModifyMonitoredItemsResponseEncodingDefaultXml', 765],
  ['ModifyMonitoredItemsResponseEncodingDefaultBinary', 766],
  ['SetMonitoringModeRequest', 767],
  ['SetMonitoringModeRequestEncodingDefaultXml', 768],
  ['SetMonitoringModeRequestEncodingDefaultBinary', 769],
  ['SetMonitoringModeResponse', 770],
  ['SetMonitoringModeResponseEncodingDefaultXml', 771],
  ['SetMonitoringModeResponseEncodingDefaultBinary', 772],
  ['SetTriggeringRequest', 773],
  ['SetTriggeringRequestEncodingDefaultXml', 774],
  ['SetTriggeringRequestEncodingDefaultBinary', 775],
  ['SetTriggeringResponse', 776],
  ['SetTriggeringResponseEncodingDefaultXml', 777],
  ['SetTriggeringResponseEncodingDefaultBinary', 778],
  ['DeleteMonitoredItemsRequest', 779],
  ['DeleteMonitoredItemsRequestEncodingDefaultXml', 780],
  ['DeleteMonitoredItemsRequestEncodingDefaultBinary', 781],
  ['DeleteMonitoredItemsResponse', 782],
  ['DeleteMonitoredItemsResponseEncodingDefaultXml', 783],
  ['DeleteMonitoredItemsResponseEncodingDefaultBinary', 784],
  ['CreateSubscriptionRequest', 785],
  ['CreateSubscriptionRequestEncodingDefaultXml', 786],
  ['CreateSubscriptionRequestEncodingDefaultBinary', 787],
  ['CreateSubscriptionResponse', 788],
  ['CreateSubscriptionResponseEncodingDefaultXml', 789],
  ['CreateSubscriptionResponseEncodingDefaultBinary', 790],
  ['ModifySubscriptionRequest', 791],
  ['ModifySubscriptionRequestEncodingDefaultXml', 792],
  ['ModifySubscriptionRequestEncodingDefaultBinary', 793],
  ['ModifySubscriptionResponse', 794],
  ['ModifySubscriptionResponseEncodingDefaultXml', 795],
  ['ModifySubscriptionResponseEncodingDefaultBinary', 796],
  ['SetPublishingModeRequest', 797],
  ['SetPublishingModeRequestEncodingDefaultXml', 798],
  ['SetPublishingModeRequestEncodingDefaultBinary', 799],
  ['SetPublishingModeResponse', 800],
  ['SetPublishingModeResponseEncodingDefaultXml', 801],
  ['SetPublishingModeResponseEncodingDefaultBinary', 802],
  ['NotificationMessage', 803],
  ['NotificationMessageEncodingDefaultXml', 804],
  ['NotificationMessageEncodingDefaultBinary', 805],
  ['MonitoredItemNotification', 806],
  ['MonitoredItemNotificationEncodingDefaultXml', 807],
  ['MonitoredItemNotificationEncodingDefaultBinary', 808],
  ['DataChangeNotification', 809],
  ['DataChangeNotificationEncodingDefaultXml', 810],
  ['DataChangeNotificationEncodingDefaultBinary', 811],
  ['StatusChangeNotification', 818],
  ['StatusChangeNotificationEncodingDefaultXml', 819],
  ['StatusChangeNotificationEncodingDefaultBinary', 820],
  ['SubscriptionAcknowledgement', 821],
  ['SubscriptionAcknowledgementEncodingDefaultXml', 822],
  ['SubscriptionAcknowledgementEncodingDefaultBinary', 823],
  ['PublishRequest', 824],
  ['PublishRequestEncodingDefaultXml', 825],
  ['PublishRequestEncodingDefaultBinary', 826],
  ['PublishResponse', 827],
  ['PublishResponseEncodingDefaultXml', 828],
  ['PublishResponseEncodingDefaultBinary', 829],
  ['RepublishRequest', 830],
  ['RepublishRequestEncodingDefaultXml', 831],
  ['RepublishRequestEncodingDefaultBinary', 832],
  ['RepublishResponse', 833],
  ['RepublishResponseEncodingDefaultXml', 834],
  ['RepublishResponseEncodingDefaultBinary', 835],
  ['TransferResult', 836],
  ['TransferResultEncodingDefaultXml', 837],
  ['TransferResultEncodingDefaultBinary', 838],
  ['TransferSubscriptionsRequest', 839],
  ['TransferSubscriptionsRequestEncodingDefaultXml', 840],
  ['TransferSubscriptionsRequestEncodingDefaultBinary', 841],
  ['TransferSubscriptionsResponse', 842],
  ['TransferSubscriptionsResponseEncodingDefaultXml', 843],
  ['TransferSubscriptionsResponseEncodingDefaultBinary', 844],
  ['DeleteSubscriptionsRequest', 845],
  ['DeleteSubscriptionsRequestEncodingDefaultXml', 846],
  ['DeleteSubscriptionsRequestEncodingDefaultBinary', 847],
  ['DeleteSubscriptionsResponse', 848],
  ['DeleteSubscriptionsResponseEncodingDefaultXml', 849],
  ['DeleteSubscriptionsResponseEncodingDefaultBinary', 850],
  ['RedundancySupport', 851],
  ['ServerState', 852],
  ['RedundantServerDataType', 853],
  ['RedundantServerDataTypeEncodingDefaultXml', 854],
  ['RedundantServerDataTypeEncodingDefaultBinary', 855],
  ['SamplingIntervalDiagnosticsDataType', 856],
  ['SamplingIntervalDiagnosticsDataTypeEncodingDefaultXml', 857],
  ['SamplingIntervalDiagnosticsDataTypeEncodingDefaultBinary', 858],
  ['ServerDiagnosticsSummaryDataType', 859],
  ['ServerDiagnosticsSummaryDataTypeEncodingDefaultXml', 860],
  ['ServerDiagnosticsSummaryDataTypeEncodingDefaultBinary', 861],
  ['ServerStatusDataType', 862],
  ['ServerStatusDataTypeEncodingDefaultXml', 863],
  ['ServerStatusDataTypeEncodingDefaultBinary', 864],
  ['SessionDiagnosticsDataType', 865],
  ['SessionDiagnosticsDataTypeEncodingDefaultXml', 866],
  ['SessionDiagnosticsDataTypeEncodingDefaultBinary', 867],
  ['SessionSecurityDiagnosticsDataType', 868],
  ['SessionSecurityDiagnosticsDataTypeEncodingDefaultXml', 869],
  ['SessionSecurityDiagnosticsDataTypeEncodingDefaultBinary', 870],
  ['ServiceCounterDataType', 871],
  ['ServiceCounterDataTypeEncodingDefaultXml', 872],
  ['ServiceCounterDataTypeEncodingDefaultBinary', 873],
  ['SubscriptionDiagnosticsDataType', 874],
  ['SubscriptionDiagnosticsDataTypeEncodingDefaultXml', 875],
  ['SubscriptionDiagnosticsDataTypeEncodingDefaultBinary', 876],
  ['ModelChangeStructureDataType', 877],
  ['ModelChangeStructureDataTypeEncodingDefaultXml', 878],
  ['ModelChangeStructureDataTypeEncodingDefaultBinary', 879],
  ['Range', 884],
  ['RangeEncodingDefaultXml', 885],
  ['RangeEncodingDefaultBinary', 886],
  ['EUInformation', 887],
  ['EUInformationEncodingDefaultXml', 888],
  ['EUInformationEncodingDefaultBinary', 889],
  ['ExceptionDeviationFormat', 890],
  ['Annotation', 891],
  ['AnnotationEncodingDefaultXml', 892],
  ['AnnotationEncodingDefaultBinary', 893],
  ['ProgramDiagnosticDataType', 894],
  ['ProgramDiagnosticDataTypeEncodingDefaultXml', 895],
  ['ProgramDiagnosticDataTypeEncodingDefaultBinary', 896],
  ['SemanticChangeStructureDataType', 897],
  ['SemanticChangeStructureDataTypeEncodingDefaultXml', 898],
  ['SemanticChangeStructureDataTypeEncodingDefaultBinary', 899],
  ['EventNotificationList', 914],
  ['EventNotificationListEncodingDefaultXml', 915],
  ['EventNotificationListEncodingDefaultBinary', 916],
  ['EventFieldList', 917],
  ['EventFieldListEncodingDefaultXml', 918],
  ['EventFieldListEncodingDefaultBinary', 919],
  ['HistoryEventFieldList', 920],
  ['HistoryEventFieldListEncodingDefaultXml', 921],
  ['HistoryEventFieldListEncodingDefaultBinary', 922],
  ['IssuedIdentityToken', 938],
  ['IssuedIdentityTokenEncodingDefaultXml', 939],
  ['IssuedIdentityTokenEncodingDefaultBinary', 940],
  ['NotificationData', 945],
  ['NotificationDataEncodingDefaultXml', 946],
  ['NotificationDataEncodingDefaultBinary', 947],
  ['AggregateConfiguration', 948],
  ['AggregateConfigurationEncodingDefaultXml', 949],
  ['AggregateConfigurationEncodingDefaultBinary', 950]
])
