name: ci

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.8'
      - run: npm ci
      - run: npm run tsc
      - run: npm run prettier:ci
      - run: npm run eslint
      - run: npm test

      - name: post coverage
        env:
          SERIESCI_TOKEN: ${{ secrets.SERIESCI_TOKEN }}
        run: |
          npm t -- --coverage --coverageReporters="text-summary" | grep Statements | awk '{print $3}' | xargs -I {} curl \
            --header "Authorization: Token ${SERIESCI_TOKEN}" \
            --data-urlencode value="{}" \
            --data sha="$(git rev-parse HEAD)" \
            https://seriesci.com/api/HBM/opcua/coverage/one
